lerna-lite/lerna-lite

- packages/core/src/__tests__/child-process.spec.ts
- packages/core/src/child-process.ts
- packages/core/src/utils/check-working-tree.ts
- packages/core/src/utils/collect-uncommitted.ts
- packages/publish/src/publishCommand.ts
- add child-process unit tests
> fix(core): catch of error should work with `exitCode` and/or `code`

- packages/version/src/__tests__/__snapshots__/version-command.spec.ts.snap
- packages/version/src/__tests__/update-lockfile-version.spec.js
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/__tests__/version-lifecycle-scripts.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
- packages/version/src/version-command.ts
- previous code was opening the project root lockfile over and over (for every workspace package) and this was causing perf issue but also in some cases potential racing condition because the processes of loading/writing json are `async` however that should really be done only once (loading lockfile once, looping through all pkg, then writing final json once)
- this code is only useful when the project has a `package-lock.json` (v2 lockfile) in the project root (when created from an NPM Workspace), which is exactly the structure of Lerna-Lite
> fix(version): load & write project root lockfile v2 only once

- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package.ts
- packages/publish/README.md
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.test.js
- packages/publish/src/publish-command.ts
- packages/version/README.md
- packages/version/src/version-command.ts
- when releasing the `workspace:` protocol, it was found afterward that it wasn't stricly following the pnpm/yarn workspace protocol where `workspace:*` should be exact range "1.5.0" and `workspace:~` a patch range "~1.5.0", this PR adds this as an option to the `publish` command **and enables it as the new default** (most users will want that) but can be disabled if required
- this is a bit of Breaking Change for whoever started using the `workspace:` protocol with previous version `1.2.0` that was released earlier
- the new flag name is `--workspace-strict-match` (default: `true`)
> feat(publish): `workspace:*` (or ~) protocol should strictly match range

- README.md
- package.json
- packages/cli/src/cli-commands/cli-init-commands.ts
- packages/core/src/__tests__/command.spec.ts
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/core/src/package.ts
- packages/core/src/project/project.ts
- packages/core/src/utils/__tests__/output.spec.ts
- packages/init/README.md
- packages/init/src/__tests__/__fixtures__/updates/package.json
- packages/init/src/__tests__/init-command.spec.ts
- packages/init/src/init-command.ts
- packages/run/src/__tests__/run-command.spec.ts
- add new option `--use-workspaces`
- create `packages` property in "lerna.json" unless `--use-workspaces` is enabled which will create "workspaces" property in "package.json" file
> fix(init): add missing packages/workspaces when initializing project

- jest/setup-unit-test-timeout.js
- package-lock.json
- package.json
- packages/core/package.json
- packages/core/src/utils/__tests__/run-lifecycle.spec.ts
- packages/core/src/utils/defaults.ts
- packages/core/src/utils/run-lifecycle.ts
Fixes #60 by following PR [#3134](https://github.com/lerna/lerna/pull/3134) it follows the same code change as original Lerna PR, as they quoted:
> We are classing this as a breaking change because the APIs of npm-lifecycle and @npmcli/run-script are significantly different, despite @npmcli/run-script being the official successor to npm-lifecycle.
> We have successfully made the integration test suite we inherited pass with this change, but there may potentially be aspects related to it which are not covered by the tests and are breaking. If you encounter any issues you believe are related to this change please open a new issue with a dedicated reproduction for us to look into!
Side note, I will not do a `major` bump for this, I decided to go with a simple `minor` (feature) bump
added …
> fix(core): replace `npm-lifecycle` with `@npmcli/run-script`, fixes #60

- packages/version/src/__tests__/__snapshots__/version-command.spec.ts.snap
- packages/version/src/__tests__/__snapshots__/version-conventional-commits.spec.ts.snap
- packages/version/src/__tests__/version-bump-prerelease.spec.ts
- packages/version/src/version-command.ts
improve default git publish message (when `message` isn't provided), closes #185
the previous default message was `"Publish"` and the new message is now `"chore: Publish new release"` to make it more aligned to conventional commits
improve default message as requested in issue #185
modify current unit tests
> fix(version): improve default git publish message, closes #185

- packages/version/src/__tests__/update-lockfile-version.spec.js
- packages/version/src/lib/update-lockfile-version.ts
provide better error message when trying to sync a different lock file than expected when using a different client other than npm, fixes #214
issue #214 was open for a potential problem but it turns out that `npmClient` was missing and the error message was not clear and concise enough to help the user, this PR should make it clearer
> fix(version): add better msg for missing `npmClient` with sync lock, fixes #214

- .github/workflows/main.yml
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package.ts
- packages/publish/src/__tests__/__fixtures__/workspace-protocol-specs/packages/package-6/package.json
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.test.js
- packages/publish/src/publish-command.ts
`workspace:` prefix should be removed on every dependencies being published
we shouldn't publish dependencies with `workspace:` even for external dependencies (not handled by Lerna-Lite), fixes #200
> fix(version): remove `workspace:` prefix on external deps, fixes #200

- packages/core/src/package.ts
- packages/publish/src/publish-command.ts
expand on #219 and also remove `workspace:` prefix on external peerDependencies as well
> fix(version): remove `workspace:` prefix on peerDeps & few refactor

- package.json
- packages/version/src/__tests__/update-lockfile-version.spec.js
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
Last version of pnpm [v7.4.0](https://github.com/pnpm/pnpm/releases/tag/v7.4.0) has a change to exit early on `install --lockfile-only` and that is impacting (aka failing) the `version` unit tests which use pnpm, it seems to be exiting too early and skipping the lock file update which defeat the purpose of the `--sync-workspace-lock` flag.
Adding `--fix-lockfile` to pnpm seems to be help to get previous pnpm behavior. I wish that `--lockfile-only` would still work but the `--fix-lockfile` flag is a quick fix for now until pnpm addresses this regression [issue](https://github.com/pnpm/pnpm/issues/4951) that I opened in the pnpm project.
```ts
pnpm install --lockfile-only --fix-lockfile
```
quick (patch) fix for issue #234 
re-enable previously failing unit tests with pnpm and find a way to …
> fix(version): `--sync-workspace-lock` flag no longer work because of pnpm regression

- packages/version/src/__tests__/update-lockfile-version.spec.js
- packages/version/src/lib/update-lockfile-version.ts
to fix a regression or a change in behavior with pnpm 7.4.0, the pnpm maintainer is suggesting to use `pnpm i --lockfile-only --no-frozen-lockfile`  instead of `--fix-lockfile`
possible fix for issue #234
> fix(version): use `--no-frozen-lockfile` instead of `--fix-lockfile`, fixes #234

- packages/changed/src/__tests__/changed-command.spec.ts
- packages/core/src/project/project.ts
- packages/diff/src/__tests__/__snapshots__/diff-command.spec.ts.snap
- packages/diff/src/__tests__/diff-command.spec.ts
- packages/diff/src/diff-command.ts
- packages/init/src/init-command.ts
- packages/version/src/__tests__/version-ignore-changes.spec.ts
previous commit was typed as `Promise<string[]>` when it's actually a sync process and should be `string[]`
> chore: use correct array type on `packageParentDirs` prop

- packages/version/src/__tests__/update-lockfile-version.spec.js
- packages/version/src/lib/update-lockfile-version.ts
- rollback PR #236 since the regression introduced in pnpm 7.4.0 was fixed in pnpm 7.4.1 and it should be safe to rollback to previous code without the need for `--no-frozen-lockfile` flag anymore to update the lock file after executing a new `version`
simpler code to update lock file to keep the same approach that it was before the recent pnpm regression
> fix(version): rollback previous patch on pnpm lockfile update

- packages/publish/README.md
This simple PR adds an additional info regarding how to handle NPM automation tokens when using `lerna` to the README of the `publish` command.
The is an issue whilst using lerna publish with the npm automation token. References issue Lerna [PR 2788](https://github.com/lerna/lerna/issues/2788) and [PR 2825](https://github.com/lerna/lerna/pull/2825)
NPM automation tokens work only with `--no-verify-access` flag provided. That was tested by me and other users (look into the issue linked above).
> docs: add info about npm automation tokens

- packages/run/package.json
- packages/run/src/__fixtures__/powered-by-nx/packages/package-1/package.json
- packages/run/src/__tests__/run-command.spec.ts
- packages/run/src/run-command.ts
- pnpm-lock.yaml
Adds double-quotes around script target when running with Nx (for example `"dev:build": "tsc build"`)
follows bug fix pushed in original Lerna [PR 3218](https://github.com/lerna/lerna/pull/3218)
> fix(run): add double quotes around script target containing colon

- package.json
- pnpm-lock.yaml
fix failure identified by Renovate because "@jest/types" is now a peer dependency in "ts-jest"
> chore(deps): add missing peer dependency "jest/types"

- packages/cli/src/cli-commands/__tests__/cli-changed-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-exec-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-list-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-run-commands.spec.ts
- packages/cli/src/cli-commands/cli-changed-commands.ts
- packages/cli/src/cli-commands/cli-exec-commands.ts
- packages/cli/src/cli-commands/cli-list-commands.ts
- packages/cli/src/cli-commands/cli-run-commands.ts
add error stack when displaying missing install on optional commands
adding the error stack can be useful when the error is not actually coming from the missing optional command install, this is actually what happened in previous issue #265
> chore: add error stack to optional command when cmd pkg is not install

- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/__tests__/version-bump.spec.ts
- packages/version/src/__tests__/version-ignore-changes.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
Use `import fs from 'fs'` instead of `from 'node:fs'` to keep earlier Node 14 version compatibility
fix issue #260 to keep Node 14 compatibility
same unit tests suite as before
> fix(version): Node14, import from "fs" instead of "node:fs", fixes #260

- lerna.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/conventional-commits/__tests__/conventional-commits.spec.ts
- packages/core/src/conventional-commits/update-changelog.ts
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/version/README.md
- packages/version/src/version-command.ts
Add a new flag `--changelog-include-commit-author-fullname [msg]` to specify if we want to include the git commit author's name, at the end of each changelog commit entry, this is only available when using `--conventional-commits` with changelogs. The default format will append the author's name at the end of each commit entry and wrapped in `()`, for exampe "feat: commit message (Author Name)". We could also use a custom format by providing the `%a` token. Note that in every case, the author's name will always be appended as a suffix to each changelog commit entry.
This improves the previous implementation done in PR #253, the previous implementation assumed wrongly that the author name was the same as the GitHub username while in fact it's totally different and is instead the name …
> feat(version): provide custom format to include commit author fullname

- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/core/src/models/interfaces.ts
- packages/publish/README.md
- packages/publish/src/__tests__/get-npm-username.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/lib/get-npm-username.ts
- packages/publish/src/publish-command.ts
Default `verifyAccess` to false for `publish`. Improve error message when encountering a npm automation token with verifyAccess=true.
As per original Lerna PR [3249](https://github.com/lerna/lerna/pull/3249)
> Lerna will no longer try to verify the user's access (to the npm packages they are publishing) by default during `lerna publish`. Setting the verifyAccess option will still perform the verification as before. This also removes the need to ever use `--no-verify-access`, since that is now the default behavior.
Keep in sync with original Lerna PR [3249](https://github.com/lerna/lerna/pull/3249)
> This is important because the standard for authentication to npm in a CI/CD pipeline is using a [npm automation token](https://docs.npmjs.com/creating-and-viewing-access-tokens). These tokens …
> feat(publish): disable legacy `verifyAccess` behavior by default

- packages/version/src/version-command.ts
stdio should be inherited so the script can be interactive while executing `lerna version`
keep in sync with Lerna, this came from Lerna [PR 3264](https://github.com/lerna/lerna/pull/3264)
> fix(version): inherit stdio for lerna version lifecycle scripts

- packages/core/src/models/interfaces.ts
- packages/core/src/utils/__tests__/run-lifecycle.spec.ts
- packages/core/src/utils/run-lifecycle.ts
- packages/publish/src/lib/npm-publish.ts
- packages/publish/src/lib/pack-directory.ts
As per original Lerna PR 3262
> During the difficult migration from npm-lifecycle to @npmcli/run-script (because of lack of details from npm) we missed the fact (because it is undocumented) that npm-lifecycle actually maintains a queue for lifecycle processes and so even though they are eagerly invoked they will complete in series.
> This PR adds back some equivalent behavior to the new usage with @npmcli/run-script by utilizing the existing p-queue library that lerna depends upon.
> It also enables a streaming/process inheritance based approach for the "let lerna publish do all the things case".
As per original Lerna PR 3262
> PS. This issue was discovered as a result of troubleshooting why it was that ionic needed to downgrade from v4 to v5 here: …
> fix(run-lifecycle): lifecycle events should run to completion in series

- helpers/logging-output.ts
- packages/core/src/__mocks__/index.ts
- packages/core/src/__mocks__/output.ts
- packages/core/src/command.ts
- packages/core/src/models/interfaces.ts
- packages/core/src/package.ts
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/__tests__/publish-from-package.spec.ts
- packages/publish/src/lib/__mocks__/npm-publish.ts
- packages/publish/src/publish-command.ts
- packages/tsconfig.bundle.json
- packages/tsconfig.json
- packages/version/src/lib/__mocks__/write-pkg.ts
As per original Lerna [PR 3263](https://github.com/lerna/lerna/pull/3263)
> Users can still opt into the old behavior of ignoring `devDependencies` until v6 by passing `--graph-type=dependencies`, or setting it in their `lerna.json`.
> Note: For the unit test updates it's down to the fact that in the relevant fixture, `package-3` has a `devDependency` on `package-2`, so it now comes after it in the ordering.
keep in sync with Lerna's codebase
> feat(publish): include all deps in package graph by default, allow no-sort

- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/publish-command.ts
The warning about workspace strict match shouldn't be shown when the option is undefined
The warning should really only be showing when directly using `--no-workspace-strict-match`, this fixes an issue identified in this [comment](https://github.com/ghiscoding/lerna-lite/pull/280#pullrequestreview-1056924413)
> fix(publish): should only warn when using `--no-workspace-strict-match`

- packages/exec/src/__tests__/exec-command.spec.ts
Add unit tests of `exec` command with the actual Profiler class implementation 
increase unit test coverage by using the real Profiler class
> tests: add actual Profiler class in exec command unit tests

- package.json
- packages/core/src/package-graph/package-graph.ts
- packages/diff/src/diff-command.ts
- packages/publish/src/publish-command.ts
- packages/version/src/version-command.ts
A previous PR introduced a way to "drastically reduce time taken to check for cycles" BUT had a very negative side effect reported by the Jest team [here](https://github.com/facebook/jest/pull/13097) that caused a lot of packages to not be updated when they should have and not be published on npm when they should have. This PR fixes this issue
Replicate a proposed fix from Lerna [PR 3234](https://github.com/lerna/lerna/pull/3234)
The new issue reported by the Jest team was introduced by a previous PR #7 which had a negative side effect and caused a lot of packages to not be updated before publish (only 5 were updated when it should have been 43).
> fix(core): ensure to touch all nodes in package-graph

- packages/core/src/conventional-commits/__tests__/get-commits-since-last-release.spec.ts
- packages/core/src/conventional-commits/get-commits-since-last-release.ts
- packages/core/src/conventional-commits/get-github-commits.ts
When using `lerna version --changelog-include-commits-client-login`, it wasn't always including all commits info and the reason is simply because I could have Pull Request that only get merged after a new release/tag and so these commits become older than the tag date so I cannot rely solely on the tag date.
In some cases where a Pull Request might be created in between 2 tags but only released after the last tag, the commits details were not included because the commit timestamp was older than the tag timestamp and so client login were not found for these in between PRs. This PR fixes this issue by finding the oldest commit since the last tag instead of looking solely on the tag timestamp which was not always correct.
Note
The new code to find oldest commit might not be the most …
> fix(version): get oldest commit data for changelog include commit login

- packages/core/src/conventional-commits/__tests__/get-commits-since-last-release.spec.ts
- packages/core/src/conventional-commits/get-commits-since-last-release.ts
When using option `--changelog-include-commits-client-login` we are executing a git command to identify the oldest commits since the last release, however in some cases it might return nothing, in that case we will return the tag info instead.
Fix an issue identified after running a dry-run of a release on the same day and that returned nothing, when that happens we should return the tag info.
> fix(version): commit user login, oldest commit might be undefined

- packages/core/src/conventional-commits/__tests__/get-commits-since-last-release.spec.ts
- packages/core/src/conventional-commits/get-commits-since-last-release.ts
We should use `%aI` commit author date which is not the one we're interested in.
We should use `%aI` (commit author date) instead of `%cI` because the author commit is really the person who created the commit while the `%c` is the committer which is not the one we're interested in.
> fix(version): use `%aI` to pull oldest commit author date

- __fixtures__/lockfile-leaf-v2/packages/package-1/package-lock.json
- __fixtures__/lockfile-leaf-v2/packages/package-1/package.json
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
npm lockfile v2 includes dependencies and devDependencies,
this commit updates those based on the updated package.
> Follow up of PR https://github.com/lerna/lerna/pull/3091, also update lockfile v2 packages."".dependencies and packages."".devDependencies keys.
As per Lerna [PR 3275](https://github.com/lerna/lerna/pull/3275)
> Solves an issue with npm lockfile v2, where dependencies/devDependencies are not properly updated.
> fix(version): properly update dependencies npm lockfile v2

- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/__tests__/publish-from-package.spec.ts
- packages/publish/src/publish-command.ts
- packages/version/src/__tests__/__snapshots__/version-command.spec.ts.snap
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/version-command.ts
simply add "dry-run> " prefix on version/publish prompt
to clearly identify that the user is in dry-run mode
> chore: add dry-run prefix to version/publish prompt for easier dry-run

- README.md
- lerna.json
- packages/cli/package.json
- packages/cli/schemas/lerna-schema.json
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/init/src/__tests__/init-command.spec.ts
- packages/init/src/init-command.ts
Adds a [JSON Schema](https://json-schema.org/) to `lerna.json`
As per Lerna [PR 3229](https://github.com/lerna/lerna/pull/3229)
> This change improves the developer experience of Lerna. Now, when modifying lerna.json, users can see what properties are valid and a brief description of what they do (taken from the lerna command options documentation).
> Note: All options for commands (as described in the command docs) are valid configuration options in lerna.json. They can be provided at three levels, in order of priority:
> Command line inline option
> 1. `lerna.json`, under a specific command
> 2. Top level of `lerna.json`
> 3. The JSON schema for `lerna.json` supports supplying options at both level 2 and 3 above.
> I tested the schema by changing lerna.json in this repo and observing …
> feat(cli): add JSON Schema for `lerna.json`

- packages/core/src/conventional-commits/__tests__/get-commits-since-last-release.spec.ts
- packages/core/src/conventional-commits/get-commits-since-last-release.ts
- packages/version/src/version-command.ts
When using the feature `--changelog-include-commits-client-login`, we need to find the last tag since the last release but when using `independent` mode, we need to add an extra argument to `describeRef` so that it returns the correct tag.  We should include a match pattern of `*@*` when calling `describeRef` (relates to a previously closed issue #220)
This PR should fix issue #310
I'm not using `independent` mode myself, so this fix will need to be confirmed with the user who opened the issue once a new release is available
> fix(core): use match pattern to get last tag date with independent mode

- packages/core/package.json
- packages/core/src/git-clients/GitLabClient.ts
- packages/core/src/git-clients/__tests__/GitLabClient.spec.ts
- packages/core/src/git-clients/__tests__/gitlab-client.spec.ts
- packages/core/src/git-clients/gitlab-client.ts
- packages/publish/package.json
- pnpm-lock.yaml
Follows Lerna [PR 3297](https://github.com/lerna/lerna/pull/3297)
> Remove the `whatwg-url` dependency that is no longer needed. Also fixes a lint error with the GitLabClient constructor.
as per Lerna PR
> Node v10 and above has native support for the WHATWG url specification via the global "URL" class, so a dedicated package for it is no longer needed.
as per Lerna PR
> Unit tests cover the creation of all URLs that were affected by this change (`GitLabClient.test.js` and `create-command.test.js`). Unit tests also cover the creation of the `GitLabClient`, whose arguments were rearranged for the lint fix. `GitLabClient` itself is not exported from the utility library, so it has no public consumers to worry about.
> chore: remove unnecessary `whatwg-url` dependency

- packages/version/README.md
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
We should not run pnpm install lifecycle scripts when we simply want to update `pnpm-lock.yaml`
> fix(version): ignore any scripts execution when updating pnpm lock file

- packages/core/src/conventional-commits/__tests__/get-commits-since-last-release.spec.ts
- packages/core/src/conventional-commits/get-commits-since-last-release.ts
Update regex for extracting commit date inside the `get-commits-since-last-release.ts` function, the regex has an issue related to parsing time zones. When executing `git log` with `--format="%h %aI"` option to get the oldest commit details,  [%aI](https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-emaIem) formats the author date in ISO 8601 format, then the old regex `/^"?([0-9a-f]+)\s([0-9\-T\:]*)"?$/` used to extract commit hash and date. The old regex can only parse dates with a time zone offset of **- hours** but in my case, my time zone has an offset of **+ hours**. Hence, the commit date was always `undefined` leading to all commands that call Github API with $since variable to fail with GraphqlResponseError `Variable $since of type GitTimestamp! was provided …
> fix(core): fix parsing commit date with different time zone

- package.json
- packages/changed/src/__tests__/changed-command.spec.ts
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package-graph/__tests__/package-graph.spec.ts
- packages/core/src/project/__tests__/project.spec.ts
- packages/core/src/utils/collect-updates/__tests__/lib-collect-packages.spec.ts
- packages/optional-cmd-common/package.json
- packages/publish/src/__tests__/get-unpublished-packages.spec.ts
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/run/src/__tests__/__snapshots__/run-command.spec.ts.snap
- packages/run/src/__tests__/run-command.spec.ts
- packages/version/src/__tests__/__snapshots__/update-lockfile-version.spec.ts.snap
- packages/version/src/__tests__/__snapshots__/version-command.spec.ts.snap
- pnpm-lock.yaml
Renovate failed on upgrading to Jest v29 because ts-jest has a hard dependency on v28, so let's upgrade manually. However I had to update all Jest snapshots to the new format which was the main breaking change of v29, the new format is a lot better since it is now a 1 to 1 input/output which is really nice to see
> chore(deps): upgrade to Jest v29

- .vscode/launch.json
- packages/core/src/conventional-commits/__tests__/conventional-commits.spec.ts
- packages/core/src/conventional-commits/update-changelog.ts
- packages/core/src/conventional-commits/writer-opts-transform.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/version-command.ts
providing `--changelog-include-commits-client-login` or `--changelog-include-commits-git-author` in CLI only (not from `lerna.json`) was actually parsed as an empty string and so ended up being interpreted as `false`
fixes #310 
yargs hybrid options (boolean / string) cannot be interpreted as a boolean, so if we detect an empty string, we should automatically defined it as a `true` boolean.
> fix(version): --changelog-include-commits-[x] in cli should be truthy

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/conventional-commits/__tests__/conventional-commits.spec.ts
- packages/core/src/conventional-commits/update-changelog.ts
- packages/core/src/models/command-options.ts
- packages/version/README.md
add header messages to all package changelogs
- fixes #325 
- add header message to all changelogs, not just root, with the option `--changelog-header-message` so that even if there's no changelog in the root (independent mode doesn't have root changelog)
> fix(version): `--changelog-header-message` should be added to all logs

- packages/run/src/run-command.ts
As per Lerna [PR 3315](https://github.com/lerna/lerna/pull/3315)
`_` is deprecated and **overrides** is preferred.
> chore(run): Update deprecated nx arg `_` to `__overrides__`

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-run-commands.ts
- packages/core/src/__tests__/command.spec.ts
- packages/core/src/command.ts
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/run/src/run-command.ts
> When `nx.json` is not present, packages being run will no longer include their dependencies when those dependencies would be filtered out by --scope. Using the flag `--include-dependencies` will cause them to be included again, as expected.
As per Lerna [PR 3316](https://github.com/lerna/lerna/pull/3316)
> This preserves the default behavior of `lerna run --scope` when `useNx` is true and `nx.json` does not exist.
> fix(run): exclude dependencies with `--scope` when `nx.json` is not present

- packages/run/README.md
- packages/run/src/__tests__/run-command.spec.ts
- packages/run/src/run-command.ts
> Makes `lerna run` warn the user when `--sort`, `--no-sort`, `--include-dependencies`, and `--parallel` are used with a `nx.json` file.
As per Lerna [PR 3326](https://github.com/lerna/lerna/pull/3326)
> This change is necessary to communicate that specific options are not available when using nx with a custom nx.json file.
> fix(run): warn on incompatible arguments with useNx

- packages/core/src/git-clients/__tests__/github-client.spec.ts
- packages/core/src/git-clients/github-client.ts
- packages/version/README.md
- packages/version/package.json
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/lib/create-release.ts
- pnpm-lock.yaml
When `--create-release github` is used without providing a `GH_TOKEN` environment variable, instead of throwing an error, we could use the library [new-github-release-url](https://github.com/sindresorhus/new-github-release-url) which will allow us to create a new GitHub Release with prefilled data by using the GitHub web interface, the lib is better described by the author as
> GitHub supports prefilling a new release by setting [certain search parameters](https://github.com/isaacs/github/issues/1410#issuecomment-442240267). This package simplifies generating such URL.
Avoid throwing an error when `GH_TOKEN` is not provided, we can simply provide an alternative way to create a new GitHub release by using their web interface
> feat(version): use manual GitHub web interface when `GH_TOKEN` undefined

- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/lib/create-release.ts
improve log when using the GitHub Release web interface when creating a new release
The link that gets created could become very long, so it's better to show the link as the last part and moving all other text info before the link itself
> chore(version): change text in logs when using github release web interface

- packages/run/README.md
- packages/run/src/__tests__/run-command.spec.ts
- packages/run/src/run-command.ts
As per original Lerna [PR 3345](https://github.com/lerna/lerna/pull/3345)
> * Only sends "targetDependencies" from Lerna to Nx when nx.json does not exist.
> * Updates the warning when using `--include-dependencies` to indicate that Lerna will send Nx additional dependencies to run.
> * Updates docs to be more clear on the differing behavior.
> * Adds a note to the docs when installing Nx that `lerna run` will behave differently and links to the page describing the differences.
stay in sync with original Lerna
> fix(run): fully defer to Nx for dep detection when nx.json exists

- packages/run/README.md
- packages/run/src/__fixtures__/powered-by-nx-with-target-defaults/lerna.json
- packages/run/src/__fixtures__/powered-by-nx-with-target-defaults/nx.json
- packages/run/src/__fixtures__/powered-by-nx-with-target-defaults/package.json
- packages/run/src/__fixtures__/powered-by-nx-with-target-defaults/packages/package-1/package.json
- packages/run/src/__fixtures__/powered-by-nx-with-target-defaults/packages/package-2/package.json
- packages/run/src/__fixtures__/powered-by-nx-with-target-defaults/packages/package-3/package.json
- packages/run/src/__fixtures__/powered-by-nx-with-target-defaults/packages/package-4/package.json
- packages/run/src/__tests__/__snapshots__/run-command.spec.ts.snap
- packages/run/src/__tests__/run-command-with-nx-no-target-defaults.spec.ts
- packages/run/src/__tests__/run-command-with-nx-not-loaded.spec.ts
- packages/run/src/__tests__/run-command.spec.ts
- packages/run/src/run-command.ts
As per Lerna [PR 3349](https://github.com/lerna/lerna/pull/3349)
> Change lerna run to only pass target dependencies to Nx when there are not target defaults already defined in nx.json
> Follow up / partial reversion of Lerna issue 3345
> fix(run): only defer to Nx when targetDefaults are defined in nx.json

- packages/publish/src/__tests__/npm-publish.spec.ts
- packages/publish/src/lib/npm-publish.ts
- packages/publish/src/models/index.ts
As per Lerna [PR 2952](https://github.com/lerna/lerna/pull/2952)
> Alias `strict-ssl` npm configuration setting to `strictSSL` publish `opts`.
> Since lerna 4, `npm_config_strict_ssl=false` is not respected by the publish process. My team publishes to an internal private registry for CI builds to avoid polluting our `npm view [package] versions` unnecessarily, but we don't (currently?) have SSL working on that garbage heap.
> 
> While `strict-ssl` is resolved out of environment and npm settings in `@lerna/npm-conf`, there's nothing downstream looking for that. [`libnpmpublish`](https://www.npmjs.com/package/libnpmpublish) passes all extra arguments directly down to [`npm-registry-fetch`](https://www.npmjs.com/package/npm-registry-fetch), but `npm-registry-fetch` is reading …
> fix(npm-publish): Allows disabling of strict SSL checks

- package.json
- packages/changed/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/exec/package.json
- packages/info/package.json
- packages/init/package.json
- packages/list/package.json
- packages/listable/package.json
- packages/optional-cmd-common/package.json
- packages/publish/package.json
- packages/run/package.json
- packages/version/package.json
bump Node min version from 14.15.0 to at least >=14.17.0 to align with recent dependencies upgrades like `pacote`, `npm-registry-fetch`, `ssri` and `write-file-atomic`
to stay compatible with recent external dependencies upgrades
> fix: bump min Node version to >=14.17.0 to align with external deps

- __fixtures__/lockfile-pnpm/packages/package-2/package.json
- __fixtures__/lockfile-pnpm/packages/package-4/package.json
- packages/cli/schemas/lerna-schema.json
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/command.ts
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/core/src/package-graph/__tests__/package-graph.spec.ts
- packages/core/src/package-graph/package-graph.ts
- packages/core/src/package.ts
- packages/core/src/utils/query-graph.ts
- packages/publish/README.md
- packages/publish/src/__tests__/__fixtures__/workspace-protocol-specs/packages/package-5/package.json
- packages/publish/src/__tests__/__fixtures__/workspace-protocol-specs/packages/package-6/package.json
- packages/publish/src/__tests__/__fixtures__/workspace-protocol-specs/packages/package-7/package.json
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
- packages/publish/src/publish-command.ts
- packages/version/README.md
- packages/version/src/version-command.ts
- supersede #362
Add a new option `--allow-peer-dependencies-update`  option on the version command which will help to update peer dependencies before publishing them. This option is opt-in and disabled by default because of what the original Lerna maintainer wrote in Lerna issue [#1018](https://github.com/lerna/lerna/issues/1018)
> `peerDependencies` shouldn't be updated by `lerna publish`
This option is not recommended for most users, for them `peerDependencies` will remain untouched unless the user really wants it enabled and has more knowledge in this regard. However even when this flag is enabled, it will never mutate/update peer dependencies with semver range operator (ie `>=2.0.0`).
Regex used
For this implementation, we'll use this regex to identify if the peer dependency is …
> feat(version): add `--allow-peer-dependencies-update`, closes #333

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-run-commands.ts
- packages/core/src/models/command-options.ts
- packages/run/README.md
- packages/run/src/run-command.ts
As per Lerna [3375](https://github.com/lerna/lerna/pull/3375)
> Makes one subcomponent of the change of default task runner more explicit, namely the automatic loading of .env files.
> Also adds a flag to allow users to disable this behavior if they wish (added as a fix because it was an oversight for the v6 release)
keep in sync with Lerna
> fix(run): allow for loading of env files to be skipped

- packages/core/package.json
- packages/core/src/package.ts
- packages/publish/package.json
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
- pnpm-lock.yaml
As per `npm-package-arg` (npa) new version 10.x PR which is a Breaking Change
> Right now, `name@` and `name` are parsed with `{type:'tag', fetchSpec: 'latest'}`, but `name@*` is parsed as `{type: 'range'}`. But since `''` is a valid semver range, it should be parsed the same as `*`.
> 
> This also saves npm-package-arg from guessing the default tag, which currently poses some semantic hazards. npm (via npm-pick-manifest) will prefer its default tag if given a range that includes it. But `name@latest` should always and only resolve to that specific version in the dist-tags. So npm-pick-manifest and pacote have to detect this and do some extra work to figure out if `latest` was actually specified or just guessed as a default.
> 1. `npa('name@')`
> 2. `npa('name')`
> 3. `npa('name@*')`
> …
> fix(deps): npm-package-arg now normalize x, x@, x@*

- packages/publish/package.json
- packages/publish/src/__tests__/verify-npm-package-access.spec.ts
- packages/publish/src/lib/verify-npm-package-access.ts
- pnpm-lock.yaml
The external lib `libnpmaccess` was rewritten to be more aligned with npm as per this [commit](https://github.com/npm/cli/commit/854521baa49ef88ff9586ec2cc5f1fbaee7fa364) (describe below) with their new release v7.x and we use 1 method from that lib which require an update on our side
> feat(rewrite): Rewrite libnpmaccess
> BREAKING CHANGE: the api for libnpmaccess is different now
> It is aligned more with how npm uses it, consolidating the mfa functions into a
single command, and renames the functions to be easier to eventually
consolidate into a registry client library.
To keep Lerna-Lite up to date with dependencies, we have to do some changes since the external lib `libnpmaccess` was rewritten and the since method `lsPackages()` that we use was to renamed to `getPackages()`. It …
> fix(deps): libnpmaccess was rewritten, lsPackages is now getPackages

- .github/workflows/main.yml
`set-output` command that was used in GitHub Action Workflow is now deprecated and throws a warning in the console
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Remove deprecated `set-output` and replace by the new way of using variables in Workflow
> chore: replace deprecated `set-output` in GitHub Action Workflows

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/conventional-commits/__tests__/__fixtures__/prerelease-independent/lerna.json
- packages/core/src/conventional-commits/__tests__/__fixtures__/prerelease-independent/package.json
- packages/core/src/conventional-commits/__tests__/__fixtures__/prerelease-independent/packages/package-1/package.json
- packages/core/src/conventional-commits/__tests__/__fixtures__/prerelease-independent/packages/package-2/package.json
- packages/core/src/conventional-commits/__tests__/__fixtures__/prerelease-independent/packages/package-3/package.json
- packages/core/src/conventional-commits/__tests__/conventional-commits.spec.ts
- packages/core/src/conventional-commits/recommend-version.ts
- packages/core/src/models/command-options.ts
- packages/version/README.md
- packages/version/src/__tests__/version-conventional-commits.spec.ts
- packages/version/src/version-command.ts
Adds possibility to force a version bump, even if already existing version is a prerelease version. This is achieved by introducing a new flag for `lerna version` command named `--conventional-bump-prerelease`.
As per Lerna [PR 3362](https://github.com/lerna/lerna/pull/3362)
> Adds new flag `--conventional-bump-prerelease` to force a version bump, if required according to conventional commits. When run with this flag, `lerna version` will release with bumped prerelease versions, even if already released packages are prereleases. Releases all unreleased changes as pre(patch/minor/major/release) by prefixing the version recommendation from `conventional-commits` with `pre`, eg. if present changes include a feature commit, the recommended bump will be `minor`, so this flag will result in a …
> feat(version): bump prerelease versions from conventional commits

- .github/renovate.json5
- package.json
- packages/run/src/__tests__/run-command-with-nx-no-target-defaults.spec.ts
- packages/run/src/__tests__/run-command.spec.ts
- packages/run/src/run-command.ts
- pnpm-lock.yaml
As per Lerna PR 3432
> Detect custom, package-specific Nx configuration in package.json files.
> Updates Lerna run to consider Nx configuration within package.json files when determining whether or not to tell Nx mimic Lerna default behavior regarding including project dependencies in running tasks.
Addresses Lerna issue 3407
> Task Dependencies Not Run When Exclusively Using Project-Specific Target Configurations
> fix(run): detect Nx target configuration in package.json files

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
- packages/version/src/version-command.ts
As per Lerna PR 3434
> Adds configured npmClientArgs to the npm install command that happens at the end of lerna version.
Addresses Lerna issue 3386
> lerna version does not take npmClientArgs into account
> feat(version): use npmClientArgs in npm install after lerna version

- packages/cli/schemas/lerna-schema.json
As per Lerna PR 3441
> This references the version 2.2.0 from the following repository. https://github.com/conventional-changelog/conventional-changelog-config-spec
> The current schema only allow for a string based "changelogPreset", but lerna also supports an object syntax for this property.
> Linked the proposed changes to one of my monorepos' `lerna.json` by adding a `$schema` at the beginning of the file, it works.
> fix(schema): add the other format changelogPreset can assume

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/core/src/models/command-options.ts
- packages/publish/README.md
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/publish-command.ts
- Outputs the packages and versions from publishing to a JSON file.
As per Lerna [PR 2653](https://github.com/lerna/lerna/pull/2653)
> When `lerna publish --summary-file <path-to-file>` It'll create a file to easily see what's been published and what version has been. Happy to rename --summary-file to something more meaningful
> 
> ```js
> [
>     {
>         "packageName": "package1",
>         "version": "v1.0.1-alpha"
>     },
>     {
>         "packageName": "package2",
>         "version": "v2.0.1-alpha"
>     }
> ]
> ```
> When creating a release you don't get a definitive and easy way to see whats changed in a nice output especially if its a pre-release(canary), So added the ability to output a JSON object to a file which would look something like this. #2053
>
> feat(publish): add --summary-file option

- packages/version/README.md
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
Allow passing multiple `npmClientArgs` to `lerna version`, for example
```sh
lerna version 3.3.3 --sync-workspace-lock --npm-client-args="--legacy-peer-deps,--force"
```
Keep in sync with Lerna and follow extra commits in Lerna [PR 3434](https://github.com/lerna/lerna/pull/3434)
added necessary unit tests
> feat(version): allow passing multiple npmClientArgs as CSV

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/version/README.md
- packages/version/src/__tests__/git-tag.spec.ts
- packages/version/src/lib/git-tag.ts
- packages/version/src/types/index.ts
- packages/version/src/version-command.ts
As per Lerna [PR 2760](https://github.com/lerna/lerna/pull/2760)
> Added support to override the executed command for `git tag` via CLI options and `lerna.json` entry.
> Some CD/CI systems have no direct write access to the repository and are not able to tag the normal way via git. An optional wrapper command/alias might be defined.
> * Added  unit-tests
> * `./core/lerna/cli.js version -h` shows new option
> feat(version): support custom command for git tag

- packages/core/src/__tests__/command.spec.ts
- packages/core/src/command.ts
- packages/core/src/project/project.ts
As per Lerna [PR 3424](https://github.com/lerna/lerna/pull/3424)
> When running a lerna command and no version is present in lerna.json configuration following error message is printed:
> 
> ```shell
> lerna ERR! ENOLERNA `lerna.json` does not exist, have you run `lerna init`?
> ```
> 
> As described in (https://github.com/lerna/lerna/issues/3311) this is not completely correct.
> 
> Additional check is added during command validation to prove a version is available in lerna.json file. In addition the check for having a lerna configuration (lerna.json) available is adapted to really check for existance of the config file. This is achieved by setting an additional flag configNotFound in the project object during lerna.json retrival.
> 
> Improve error messages for invalid lerna.json to …
> fix(core): more detailed error message when version cannot be found

- .github/renovate.json5
- .npmrc
- package.json
- packages/changed/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/exec/package.json
- packages/info/package.json
- packages/init/package.json
- packages/list/package.json
- packages/listable/package.json
- packages/optional-cmd-common/package.json
- packages/publish/package.json
- packages/run/package.json
- packages/version/package.json
- pnpm-lock.yaml
add `rimraf` npm script to all individual packages
the new version of `rimraf` removes support to Glob patterns, let's stick with previous version in Renovate for now since they might bring in it back in future release
> chore(deps): add rimraf dist to all packages & stay on older version

- lerna.json
- package.json
- packages/watch/src/__tests__/watch-command.spec.ts
- packages/watch/src/watch-command.ts
The `--glob` option should work with/without the slash prefix when appended to the package path to watch
Prior to this PR, we had to always remember to include the `/` prefix on the `--glob` option, but we shouldn't have to do that
add and update unit tests
> fix(watch): glob should work without slash prefix

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-watch-commands.ts
- packages/core/src/models/command-options.ts
- packages/watch/README.md
- packages/watch/src/__tests__/watch-command.spec.ts
Chokidar option [`awaitWriteFinish`](https://github.com/paulmillr/chokidar#performance) can be both a complex object (that we provided in previous PR) and a boolean (this PR)
We should be able to provide `awaitWriteFinish` as both available Chokidar type a boolean and a complex object
> fix(watch): add missing Chokidar option awaitWriteFinish as a boolean

- package.json
- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-watch-commands.ts
- packages/core/src/models/command-options.ts
- packages/watch/README.md
- packages/watch/src/__tests__/watch-command.spec.ts
- packages/watch/src/watch-command.ts
Add `--stream` option to `lerna watch`
We should add the same `--stream` option as every other commands like `exec` and `run`
add unit tests
> fix(watch): add missing --stream option

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-watch-commands.ts
- packages/core/src/models/command-options.ts
- packages/core/src/utils/query-graph.ts
- packages/watch/README.md
- packages/watch/src/__tests__/watch-command.spec.ts
- packages/watch/src/constants.ts
- packages/watch/src/index.ts
- packages/watch/src/models.ts
- packages/watch/src/watch-command.ts
cleanup the `watch` command
- in most cases people would want to watch for not just file update but also file add/remove as well and also for the performance point of view I don't think there will be much difference since they are the same file being watched
- the other problem by watching g chokidar events separately was that it was triggering too many lerna watch events
- this also makes the code a lot smaller and easier to follow and troubleshoot
- I'm doing this now since I doubt many people downloaded it in 2 days and even if they did, the difference is still small and manageable
> chore(watch): watch command should watch for chokidar events

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-watch-commands.ts
- packages/core/src/models/command-options.ts
- packages/watch/README.md
- packages/watch/src/__tests__/watch-command.spec.ts
- packages/watch/src/watch-command.ts
`lerna watch` should ignore certain folders by default 
in a Lerna-Lite monorepo, there are common folders that should most often be skipped by default: `.git`, `dist` and `node_modules`
> fix(watch): lerna watch should ignore git, dist & node_modules folders

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/core/src/models/command-options.ts
- packages/publish/src/__tests__/publish-lifecycle-scripts.spec.ts
- packages/publish/src/publish-command.ts
Deprecate lerna publish option `--require-scripts`
This option has been half deprecated for a long time in Lerna and even had a PR to remove it but it was never merged, so let's remove it for good in our next major version. (ref Lerna [PR 1862](https://github.com/lerna/lerna/pull/1862))
> fix(publish): deprecate publish --require-scripts

- packages/cli/schemas/lerna-schema.json
Use the correct type in JSON Schema `--contents` property
The option `--contents` should be of type `string`. It was also a good time to review the entire JSON Schema and remove properties that aren't available in Lerna-Lite (ie: lerna `add`, `create`, `link` should all be removed since they will never be part of Lerna-Lite)
fixes #466
> fix(schema): `--contents` type should be string, fixes #466

- .vscode/launch.json
- helpers/cli.ts
- packages/core/src/__mocks__/collect-updates.ts
- packages/core/src/utils/__tests__/npm-conf.spec.ts
- packages/core/src/utils/npm-conf.ts
- packages/exec/src/__tests__/exec-command.spec.ts
- packages/run/src/__tests__/run-command.spec.ts
- packages/version/src/lib/__mocks__/load-json-file.ts
- packages/version/src/lib/__mocks__/write-pkg.ts
- packages/watch/src/__tests__/watch-command.spec.ts
Replace as much as possible `module.exports` and `require()` by ESM imports
in preparation to be ESM ready
> chore: remove more module.exports and require()

- packages/run/README.md
Adds a note to the docs, warning users about using Yarn with `lerna run -- args`.
This is needed because it is currently unclear why `yarn lerna run test -- --myarg` won't correctly pass `--myarg` to the `test` script.
> docs(run): warn in docs about using yarn and passing args to lerna run

- packages/publish/README.md
- packages/publish/src/__tests__/npm-publish.spec.ts
- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/lib/npm-publish.ts
- packages/publish/src/publish-command.ts
As per Lerna PR 3513
> Catches the EPUBLISHCONFLICT error from npm when a version already exists. In this case, Lerna assumes that you have already published the package.
> This allows `lerna publish from-git` to be idempotent. If one or more packages fail to publish, then you can rerun `lerna publish from-git` to publish the packages that failed.
> feat(publish): recover from network failure

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-watch-commands.ts
- packages/core/src/models/command-options.ts
- packages/watch/README.md
- packages/watch/src/__tests__/watch-command.spec.ts
- packages/watch/src/constants.ts
- packages/watch/src/watch-command.ts
Use `debounce` which is a much better option name for the watch time to wait before collecting all changes
The previous option name `emit-changes-delay` wasn't very intuitive, while debounce is a common term in programming
> fix(watch): use a better debounce option name for the watch

- packages/publish/README.md
- packages/publish/package.json
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/__tests__/publish-from-package.spec.ts
- packages/publish/src/publish-command.ts
- pnpm-lock.yaml
- scripts/cleanup-temp-files.mjs
Use common removeSync from fs-extra to cleanup temp files
No need to use extra libraries like rimraf when we can simply use `fs.removeSync` which we already use to cleanup temp folders after publish execution
> chore(publish): use `fs.rmdir` instead of rimraf to cleanup publish tmp

- packages/watch/README.md
- packages/watch/src/__tests__/watch-command.spec.ts
- packages/watch/src/watch-command.ts
Rollback code that implemented stdin to watch for "x" to exit the watch, it seems problematic in some use case. 
The stdin that was added in PR #472 seems to be causing a slight problem in some cases to exit the watch, until I can find a better way to implement this, I think it's just better to simply remove it and go back to a simple Ctrl+C to close the thread/watch
> fix(watch): remove watch stdin causing problem exiting the watch

- packages/watch/src/models.ts
- packages/watch/src/watch-command.ts
Make sure all file that changed while a command is being processed are being pushed to the queue and not drop/skipped
Changes that were being queued, while an execution was in progress, were being skipped. This PR fixes this problem and makes sure that whichever files are being queued while a command is being processed won't be dropped and be part of the execution
> fix(watch): watch execution shouldn't skip queued changes

- README.md
- packages/core/src/command.ts
- packages/version/README.md
highlight the fact that `version` is a required property to exist in the `lerna.json` config
We should highlight the fact that `version` property is a required field that needs to be defined in `lerna.json`, there was a previous PR #431 that now throws an error but it wasn't clear enough that the user must really include such field in its `lerna.json` config. Closes #485
> fix(version): highlight version prop required in `lerna.json`

- package.json
- packages/watch/src/__tests__/watch-command.spec.ts
- packages/watch/src/watch-command.ts
Add code to cleanly close the Chokidar watch
It's better to add proper Chokidar watch close and process.exit` for a cleaner exiting of the watch
> chore(watch): add missing process exit and close chokidar watch cleanly

- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
When using `--sync-workspace-lock` with Yarn, we should validate that it's Yarn Berry
The `--sync-workspace-lock` option which runs  `yarn install --mode update-lockfile` will only work with Yarn Berry, so we should also make sure that the user does have the minimal Yarn version before trying to execute the command
> fix(version): validate yarn Berry >=2.0 before running yarn sync lock

- package.json
- packages/exec/README.md
When executing the command in the shell, you will need to surround the command provided to `lerna exec` in quotes (what comes after double-dash ` -- `). Without this, the entire line is interpreted by your shell before lerna ever sees it and causes command flags to be returned as unknown. For example `lerna exec -- 'git log -p -2'`. This is not required when used as an npm script.
- closes #493 
Provide necessary documentation to address issue #493, it will still require the command to be wrapped in quotes and we can't do anything to change that since that was mentioned by the original Lerna maintainer in this [comment](https://github.com/lerna/lerna/issues/1965#issuecomment-491431307)
> Yeah, woulda told you to single-quote the whole command after `--` had I seen this earlier, sorry. If …
> docs(exec): add note to wrap lerna exec commands in quotes when run from shell

- .github/renovate.json5
- Renovate just ran and latest version from `cosmiconfig` seems to causing issues, let's ignore `cosmiconfig` for now so that we can merge the other deps
ignore `cosmiconfig` which is causing PR #496 to fail, we will reenable it after PR #496 is updated without `cosmiconfig` so that we can merge the update of the other deps
> chore: exclude cosmiconfig from Renovate update for now

- package.json
- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/core/src/utils/collect-updates/__tests__/collect-updates.spec.ts
- packages/core/src/utils/collect-updates/__tests__/lib-make-diff-predicate.spec.ts
- packages/core/src/utils/collect-updates/collect-updates.ts
- packages/core/src/utils/collect-updates/lib/make-diff-predicate.ts
- packages/version/README.md
Add a new `--independent-subpackages` option to avoid shipping nested 
Closes issue #491 
> As a developer using Lerna-Lite I would love to have the possibility to work with nested packages in a way that changes to a `package B` being a subpackage of `package A` directory-wise do not lead to a version-change of `package A` on `lerna version` purely due to `git diff` but only if `package A` actaully depends on `package B`. This example reflects our current development structure but produces many new, but unnecessary, versions.
> feat(version): add `--independent-subpackages` option, closes #491

- packages/publish/src/publish-command.ts
As per Lerna [PR 3327](https://github.com/lerna/lerna/pull/3327)
> when verifyWorkingTreeClean error happend set exitCode to 0
> fixed error when run "lerna publish from-package" in package.json scripts
> 1. add publish:'lerna publish from-package" to package.json->"scripts"
> 2. exec "npm run publish" in terminal
> 3. everything well done
> fix(publish): ensure zero exit code when EWORKINGTREE warning occurs

- packages/init/README.md
- packages/init/src/__tests__/init-command.spec.ts
- packages/init/src/init-command.ts
When using `lerna init --use-workspaces`, it should also add `useWorkspaces` boolean value to the `lerna.json` file
Missing boolean value `useWorkspaces` should also be added to `lerna.json`
> fix(init): the `--use-workspaces` option should update `lerna.json`, fixes #492

- packages/version/src/version-command.ts
Tags are signed sequentially 
fixes https://github.com/lerna-lite/lerna-lite/issues/510#issue-1619420415
Simultaneously executing `git tag ... --sign` seems to be an issue. I still have no clue why exactly gpg starts to fail.
On the other hand sequentially signing even with 16 tags has a barely noticeable difference in speed compared to simultanously executing a sign requests.
Unfortunately the issue seems to be a timing issue with gpg, thus i repeated signing 10 times of which non failed.
> fix(version): sign tags sequentially to prevent gpg issues with many tags

- .npmrc
- packages/cli/schemas/lerna-schema.json
- packages/core/src/models/interfaces.ts
- packages/core/src/utils/collect-updates/__tests__/collect-updates.spec.ts
- packages/core/src/utils/collect-updates/collect-updates.ts
- packages/listable/package.json
- packages/publish/README.md
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/publish-command.ts
- packages/version/README.md
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/version-command.ts
- pnpm-lock.yaml
Add `descripteTag` in the `lerna.json` configuration to allow users to customize the tag pattern. If `descripteTag` is not configured, the tag pattern defaults to`*@*`.
However, it is not supported in `lerna publish from-git`, only in `version`, `publish -- canary`
Add feature to fix #507
> feat(publish): support git "describeTag" configuration in version/publish commands

- packages/core/src/utils/collect-updates/lib/make-diff-predicate.ts
Use correct `ignore` pattern type
Globby ignore pattern should be an array of string instead of a simple string
> fix(core): ignore globby pattern type should be an array not a string

- packages/run/src/run-command.ts
As Lerna PR 3620 for `lerna run` with Nx (only)
> Update the run command to use `runMany` when a single package matches the filter, but multiple targets are provided.
As Lerna PR
> Nx's `runOne` function cannot accept multiple targets. Because of this, Lerna currently errors in the following case:
> 
> ```
> $ lerna run --scope="my-specific-package" script1,script2
> ```
> 
> This fix makes this case use `runMany` instead, which can accept multiple targets.
>
> fix(run): only use run-one w/Nx when not passing multiple scripts

- packages/version/README.md
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
Remove support for npm version below 8.5.0 for the `--sync-workspace-lock` option, the new release will require NPM to be at least 8.5.0 so we can drop old code
The code implementation of `--sync-workspace-lock` for NPM below 8.5.0 was achieved in 2 steps instead of 1 step with NPM >=8.5.0, we had to 
1. run npm shrinkwrap lock, which created the file `npm-shrinkwrap.json`
2. then rename `npm-shrinkwrap.json` back to `package-lock.json`
but in >=8.5.0 it's achieved in 1 simple step we can simply run `npm install --package-lock-only` without any shrinkwrap
> chore(version): remove sync lock support for npm version below 8.5.0

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/core/src/models/command-options.ts
- packages/publish/src/__tests__/publish-lifecycle-scripts.spec.ts
- packages/publish/src/publish-command.ts
Remove old deprecated option `--require-scripts`, it was only used by Babel when Lerna was originally created a long time ago, it's so old that it wasn't even documented
The option `--require-scripts` have been deprecated for a very long time and using npm scripts have been the preferred approach for many years already, it also follows this Lerna [PR 1862](https://github.com/lerna/lerna/pull/1862)
> feat(publish): remove `--require-scripts`, keep npm scripts lifecycle

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/version/README.md
- packages/version/src/conventional-commits/update-changelog.ts
- packages/version/src/models/index.ts
- packages/version/src/version-command.ts
Remove unused and deprecated `--changelog-version-message`
I don't believe anyone used this option, not even me, so there's no reason to keep this option for the next major release
> feat(version): remove deprecated `--changelog-version-message` option

- packages/core/src/child-process.ts
- packages/core/src/command.ts
- packages/core/src/package.ts
- packages/core/src/project/lib/make-file-finder.ts
- packages/core/src/project/project.ts
- packages/core/src/utils/npm-conf.ts
- packages/core/src/utils/run-lifecycle.ts
- packages/exec/src/exec-command.ts
- packages/publish/src/lib/get-packed.ts
- packages/publish/src/lib/npm-dist-tag.ts
- packages/publish/src/publish-command.ts
- packages/run/src/lib/timer.ts
- packages/run/src/run-command.ts
- packages/version/src/lib/create-release.ts
- packages/version/src/utils/otplease.ts
Convert all Istanbul ignore comments to c8 ignore comments
Since we migrated from Jest to Vitest, we also also use c8 reporter which is better for ESM code, so we need to review all Istanbul ignore comments and use c8 ignore comments instead
> chore: change all istanbul ignores to c8 ignores

- packages/version/src/__tests__/__snapshots__/version-build-metadata.spec.ts.snap
- packages/version/src/conventional-commits/get-github-commits.ts
- packages/version/src/git-clients/__tests__/github-client.spec.ts
- packages/version/src/git-clients/github-client.ts
- packages/version/src/git-clients/gitlab-client.ts
- packages/version/src/lib/create-release.ts
- packages/version/src/version-command.ts
Use `await import()` instead of `require()` to be fully ESM compatible
I tried `createRequire` but that caused issue when I tried it under the conventional commits changelog creation, so I assume it might also give problems when creating GitHub Release with GHE which was loading Oktokit GHE plugin dynamic imports. Using `await import()` is more bullet proof for ESM
> feat(version): use await import instead of require() for GHE release

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/version/README.md
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/lib/create-release.ts
- packages/version/src/models/index.ts
- packages/version/src/version-command.ts
When using `independent` mode, a GitHub/GitLab release is created for each package and very often some of the package will only have a `"Version bump only for package x"` added to the changelog and a release is created even for these simple bump only package. However these kind of release are not very useful and could be skipped, this is what this option flag will provide to the user when the package is detected to be a version bump only, with this flag enabled, it will not create a release for that package
**Note** this will be available only under the new `major` v2.0.0 version and higher of Lerna-Lite
Avoid creating too many releases with info that are not that useful, most users are interested in "what changed?" and not so much in "nothing changed in package x"
unit tests only
> feat(version): add `--skip-bump-only-release` to avoid empty gh releases

- global.d.ts
- helpers/logging-output.ts
- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/publish-command.ts
As per Lerna PR 3644
> Add a warning log entry when `lerna publish` fails that includes the package name.
As per Lerna PR 
> Sometimes there error returned from the registry doesn't include the package name. For instance `ERR! E402 You must sign up for private packages`.
> feat(publish): add name of package that fails to publish

- packages/version/src/__tests__/version-conventional-commits.spec.ts
- packages/version/src/version-command.ts
The issue #569 brought up a problem where dry-run option was used to test a release (ie `--conventional-prerelease --dry-run premajor`) but when dry-run was removed it caused an unexpected result (ie `--conventional-prerelease premajor`) the latter changed the result because `premajor` was then passed to `--conventional-prerelease` which was the case with `--dry-run` in place
`--conventional-prerelease` should probably throw when an argument is provided which didn't find any packages to prerelease (that is if I understood the docs correctly), for example `--conventional-prerelease premajor` is incorrect because that is not the name of a package but providing  `--conventional-prerelease *` should work because that is equal to all packages . It should also throw if we provide something …
> fix(version): invalid --conventional-prerelease should throw, fix #569

- packages/cli/package.json
- pnpm-lock.yaml
Fixes `Cannot find package '@lerna-lite/publish' imported from ...` error for monorepo projects.
- Clone https://github.com/volarjs/workspace
- Run `$ pnpm i && npm run setup:vue`
- Run `$ cd volar && npm run release`
> fix: cannot find `publish` module if `cli` inside a monorepo package

- packages/cli/package.json
- pnpm-lock.yaml
Spreading the previous PR #573 to all command to fix the same problem but for all commands when installed as `optionalDependencies` inside a monorepo that contains a monorepo
As per PR #573, this fixes `Cannot find package '@lerna-lite/publish' imported from ...` error for monorepo projects when any of the commands are installed as `optionalDependencies` (like [Volar](https://github.com/vuejs/language-tools) does)
> fix: cannot find optional commands if `cli` inside a monorepo package

- packages/publish/package.json
- pnpm-lock.yaml
`normalize-path` should be a dependency of the `@lerna-lite/publish` package, otherwise it throws errors while running on CI.
While running a workflow on GitHub Actions, one of my packages wasn't published because the package `normalize-path` was missing. Installing it as a dependency of my repository worked, but as it is a dependency of `@lerna-lite/publish` it should be installed in the package itself instead.
No testing needed.
> fix(publish): add normalize-path as a dependency

- .github/workflows/main.yml
Node 19 will be a short live while Node 20 will enter LTS in October of this year 2023
Run CI workflow against latest NodeJS version
> chore: execute CI workflow against Node20 instead of Node19

- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package.ts
- packages/publish/src/__tests__/__fixtures__/workspace-protocol-specs/packages/package-2/package.json
- packages/publish/src/__tests__/__fixtures__/workspace-protocol-specs/packages/package-3/package.json
- packages/publish/src/__tests__/publish-licenses.spec.ts
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
- packages/version/README.md
The `peerDependencies` is a special case and will only be bumped when the flag `--allow-peer-dependencies-update` is enabled. A package set as `workspace:^` (without any semver number) should be able to be bumped and it wasn't before this PR.
The `--allow-peer-dependencies-update` implementation was only tested with `workspace:` and semver, but it wasn't tested with just `workspace:^` (or `~`) and the end result was actually producing an invalid version `^` (which is obviously wrong). 
This PR fixes 2 problems with `peerDependencies` identified in #587 and #590:
_the example below is assuming that the version is at `1.0.0` and we are processing a `minor` bump_
1. when version is `workspace:^` and `--allow-peer-dependencies-update` is enabled, the version in `package.json` should remain as …
> fix(version): allowPeerDependenciesUpdate should work w/`workspace:^`, fix #590

- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
cleanup some leftover code for the `--workspace-strict-match` that was removed in latest major 2.0 version
just code cleanup, the option no longer exist but some lines and the CLI option was forgotten
> chore: cleanup workspace-strict-match option that was removed in latest

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-run-commands.ts
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/run/README.md
- packages/run/src/__tests__/run-command.spec.ts
- packages/run/src/run-command.ts
This option doesn't seem to be used much by users, I only found 1 user out of 50 who was taking advantage of this option. So we can start the process of deprecating the option and simply remove it later in the next major version (in a year or so), so it can still be used until then
The goal of Lerna-Lite is to provide a light (lite) alternative to Lerna and since barely anyone were using this option, I don't see any reason to keep this option in the code. This will lower the code size and avoid issues whenever a new Nx version comes out. On a final note, Lerna is becoming another Nx branded product, so for sure they have the best possible integration with Nx and if the user is interested in using, then this user will probably be using Lerna anyway (instead of Lerna-Lite)
n/a
> chore(run): deprecate `lerna run --use-nx` option

- lerna.json
- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/version/README.md
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/lib/create-release.ts
- packages/version/src/models/index.ts
- packages/version/src/version-command.ts
GitHub allows us to create a discussion from a release as per this GitHub blog post [You can now link discussions to new releases](https://github.blog/changelog/2021-04-06-releases-support-comments-and-reactions-with-discussion-linking/)
This will create both a Release and Discussion. by providing a discussion category name. As per my original Discussion #602
The Octokit API that would help for this is [Octokit - create a release](https://octokit.github.io/rest.js/v19#repos-create-release) and [GitHub Rest API - create a release](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release) and the option that I need to use is `discussion_category_name`
> feat(version): add new `--create-release-discussion` option

- package.json
- packages/publish/package.json
- packages/publish/src/publish-command.ts
- pnpm-lock.yaml
- scripts/cleanup-temp-files.mjs
use `globby`, instead of `glob`, to cleanup temp files & folders
we already use `globby` in other sections of the code, so let's use the same dependency everywhere and reduce number of dependencies by 1 less
> chore: replace `glob` by `globby` to cleanup temp files

- package.json
- packages/publish/package.json
- packages/publish/src/publish-command.ts
- pnpm-lock.yaml
- scripts/cleanup-temp-files.mjs
Reverts lerna-lite/lerna-lite#605, it actually doesn't seem to work with `globby`, so let's revert and `glob` which seems to be faster than `globby` now too
> Revert "chore: replace `glob` by `globby` to cleanup temp files"

- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/version-command.ts
Just some simple code change on the new `--create-release-discussion` option
We should probably throw an error when user us trying to use `--create-release-discussion` without providing a category name
> chore(version): throw when createReleaseDiscussion missing cat name

- README.md
- packages/changed/README.md
- packages/cli/README.md
- packages/cli/src/cli-commands/cli-changed-commands.ts
- packages/cli/src/cli-commands/cli-diff-commands.ts
- packages/cli/src/cli-commands/cli-exec-commands.ts
- packages/cli/src/cli-commands/cli-list-commands.ts
- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/cli/src/cli-commands/cli-run-commands.ts
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/cli/src/cli-commands/cli-watch-commands.ts
- packages/diff/README.md
- packages/exec/README.md
- packages/init/README.md
- packages/list/README.md
- packages/publish/README.md
- packages/run/README.md
- packages/version/README.md
- packages/watch/README.md
Remove the `-W` flag from all `npm install` commands in the docs and in some error messages.
The `-W` flag is not supported by `npm`. See discussion #613.
> docs: remove `-W` flag from all `npm install`

- packages/version/src/git-clients/github-client.ts
I ran `lerna version` on my company project and tried to create a release on GitHub Enterprise and encountered the following error. (GHE_VERSION="2.19")
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/foobar/node_modules/.pnpm/@lerna-lite+version@2.4.0_@lerna-lite+publish@2.4.0/node_ modules/@octokit/plugin-enterprise-rest/ghe-v2.19'
```
On investigation, I found that `@lerna-lite/version` is an ESM, but `@octokit/plugin-enterprise-rest` is a CJS and the path resolution fails when importing the plugin.
So I tried changing the `GHE_VERSION` to `2.19/index.js` and ran the `lerna version` and that worked.
However, it is incorrect that the user of the library needs to specify `2.19/index.js` for the `GHE_VERSION`.
I have therefore created a Pull Request.
I've had success with my …
> Fix GitHub Enterprise plugin import path

- package.json
- pnpm-lock.yaml
- vitest/vitest.config.ts
remove deprecated module
`@vitest/coverage-c8` was deprecated and replaced with `@vitest/coverage-v8`
> chore: switch Vitest from deprecated C8 to new V8

- packages/cli/package.json
- packages/core/src/utils/__tests__/string-util.spec.ts
- packages/core/src/utils/string-utils.ts
- packages/publish/README.md
- packages/publish/src/__tests__/__fixtures__/remove-fields/packages/package-1/package.json
- packages/publish/src/__tests__/__fixtures__/remove-fields/packages/package-4/package.json
- packages/publish/src/__tests__/publish-remove-package-fields.spec.ts
- packages/publish/src/publish-command.ts
- packages/version/package.json
when executing `--remove-package-fields 'scripts'`, we should skip the removal of any lifecycle scripts (`prepublish`, `prepublishOnly`, `prepack`, `postpack`) because these scripts needs to be executed after the field removal process.
fixes #637 were it failed publishing because some of these lifecycle scripts were being defined crashed because at the time of the lifecycle execution the script was already deleted. 
Also note that I tried to move the execution of the field removal to after the `packUpdated()` call (as I wrote in this [comment](https://github.com/lerna-lite/lerna-lite/issues/637#issuecomment-1587816645) but then at that point it's too late to remove since we already packed the tarball, it's a chicken and egg kinda problem, so the easisst way to deal with this is to keep …
> fix(publish): skip lifecycle scripts on pkg fields removal, fixes #637

- CONTRIBUTING.md
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package-graph/__tests__/package-graph.spec.ts
- packages/core/src/project/__tests__/project.spec.ts
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/publish-licenses.spec.ts
- packages/publish/src/__tests__/publish-tagging.spec.ts
- packages/run/src/__tests__/__snapshots__/run-command.spec.ts.snap
- packages/run/src/__tests__/run-command.spec.ts
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- pnpm-lock.yaml
Add Vitest snapshot serializer to all unit tests that use snapshots
Fixes an issue with Vitest `--no-thread` which made unit tests work when run all at once but failed when ran one at a time. Basically the issue seemed to be that when run all at once it shared the global scope and were not equivalent, however adding the escape quote serializer to all unit tests makes them use the same serializer everywhere making them pass in all cases. 
ran multiple time in single mode and in all at once mode
> chore: add Vitest quote serializer everywhere to avoid no-thread diff

- packages/core/src/models/interfaces.ts
- packages/publish/src/__tests__/get-unpublished-packages.spec.ts
- packages/publish/src/lib/get-unpublished-packages.ts
- pnpm-lock.yaml
As per [Lerna PR 3747](https://github.com/lerna/lerna/pull/3747)
> There is a missing mapping of strict-ssl for unpublished projects lookup.
This results into falsy unpublished projects.
We are using lerna to automatically determine which packages are unpublished. We have encountered the issue it tries to publish packages again and again regardless if they are already published.
With debugging I have found out there is an issue using the given strict-ssl attribute. It is not passed to pacote correctly.
In general it is the same issue like here as Lerna [issue 2952](https://github.com/lerna/lerna/pull/2952)
> fix: strict-ssl mapping for node-fetch-registry during unpublished projects lookup

- packages/publish/src/publish-command.ts
As per Lerna [PR 3753](https://github.com/lerna/lerna/pull/3753)
> Catches another possible form of publish conflict error from npm.
> Some permission setups on npm were causing a 403 error instead of the EPUBLISHCONFLICT code, and this ensures they are caught appropriately.
> This has been tested manually by publishing packages to npm with conflicts, observing the error in Lerna, then testing it again with this change and observing Lerna properly swallow the error.
> fix(publish): catch publish conflict 403 error from npm

- packages/changed/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/exec/package.json
- packages/filter-packages/package.json
- packages/init/package.json
- packages/list/package.json
- packages/listable/package.json
- packages/profiler/package.json
- packages/publish/package.json
- packages/run/package.json
- packages/version/package.json
- packages/watch/package.json
better hybrid CJS/ESM support
when defining the old CJS `main` and `module`, these properties should come after `exports` (new ESM prop) so that newer NodeJS will try `exports` first (we shouldn't try the fallback first), while for old NodeJS it will automatically use the fallbacks since `exports` won't work, see this TypeScript for more info (https://www.typescriptlang.org/docs/handbook/esm-node.html)
> fix: CJS fallbacks should be at the end not at beginning

- .vscode/launch.json
- README.md
- packages/cli/schemas/lerna-schema.json
- packages/core/src/models/command-options.ts
- packages/core/src/package.ts
- packages/version/README.md
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/conventional-commits/__tests__/conventional-commits.spec.ts
- packages/version/src/conventional-commits/make-bump-only-filter.ts
- packages/version/src/lib/create-release.ts
- packages/version/src/models/index.ts
- packages/version/src/version-command.ts
Reimplement `skipBumpOnlyRelease` to make it work properly in `independent` mode and also renamed to a plural name `skipBumpOnlyReleases` which better represent the fact that it can skip multiple bump only versions.
Previous implementation was expecting that the changelog entry was only the current changes, however it turns out that it was the entire package changelog. A better implementation is to keep a boolean ref on each package and use it when it's time to create the release.
- fixes #703
> fix(version): skipBumpOnlyReleases reimplementation, fixes #703

- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/lib/is-npm-js-publish-version-conflict.ts
- packages/publish/src/lib/is-npm-pkg-github-publish-version-conflict.ts
- packages/publish/src/publish-command.ts
The version conflict recognition logic was not working for github
because it returns a different `code` for the same error compared to
what npmjs.org returns.
I've added two utility functions to check for the error code and
message to make the code more readable in the error handler of the
publish operation.
This way there is a robust detection supporting both npmjs.com and
npm.pkg.github.com registries, not just npmjs.org.
Signed-off-by: Peter Somogyvari <peter.metz@unarin.com>
I've added a new test case within the file
`packages/publish/src/__tests__/publish-from-git.spec.ts`
to cover specifically the GitHub npm registry's error code,
so now the test verifies both npmjs.org and github.com registries
error codes not just npmjs.org as before.
I've also tested it manually, on a mono-repo I …
> fix(publish): fix version conflict recognition for github packages

- packages/version/README.md
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/git-clients/__tests__/github-client.spec.ts
- packages/version/src/git-clients/__tests__/gitlab-client.spec.ts
- packages/version/src/git-clients/github-client.ts
- packages/version/src/lib/create-release.ts
add `GITHUB_TOKEN` as a valid alias to `GH_TOKEN`, in other words both environment variable will work (it will first read and use `GH_TOKEN`, if not found it will try `GITHUB_TOKEN`)
Many libraries and even GitHub Actions prefer to use `GITHUB_TOKEN` (for example [release-it](https://github.com/release-it/release-it#github-releases)) as environment variable instead of Lerna's `GH_TOKEN` which seems less popular, so this PR is now allowing both tokens to work and user can chose the variable name they prefer. This might help for compatibility since many use the name `GITHUB_TOKEN`
> feat: add `GITHUB_TOKEN` as valid alias to `GH_TOKEN`

- tsconfig.base.json
code cleaning
`paths` in `tsconfig` should be within the `compilerOptions` not outside of it like the previous code was, but if I move these `paths` inside the  `compilerOptions` then it breaks. However these paths seems unnecessary since we use `references: [{ "path": ''' }]` in packages that depends on other Lerna-Lite packages, so we should be fine
> chore: remove unused paths from tsconfig

- README.md
- lerna.jsonc
- packages/core/src/project/__fixtures__/invalid-lerna-jsonc-recoverable/lerna.jsonc
- packages/core/src/project/__fixtures__/invalid-lerna-jsonc-recoverable/package.json
- packages/core/src/project/__fixtures__/lerna-json5-config/lerna.json5
- packages/core/src/project/__fixtures__/lerna-json5-config/package.json
- packages/core/src/project/__fixtures__/lerna-jsonc-config/lerna.jsonc
- packages/core/src/project/__fixtures__/lerna-jsonc-config/package.json
- packages/core/src/project/__tests__/project.spec.ts
- packages/core/src/project/project.ts
Provide more ways to configure Lerna-Lite, because some users might prefer `.json5` since it is a more human readable config, however this comes with a side note
> **Note**  most code editors (like VSCode) only support [JSON Schema](https://json-schema.org/) and intellisense via `.json` and `.jsonc` extensions but not with `.json5`
support more file extensions to configure Lerna-Lite, on top of `lerna.json` we will now accept `lerna.jsonc` and `lerna.json5`. 
add unit tests
> feat(core): add (`.jsonc`, `.json5`) support to Lerna-Lite config

- .github/renovate.json5
- packages/version/package.json
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/local-preset-async.ts
- packages/version/src/conventional-commits/__tests__/conventional-commits.spec.ts
- packages/version/src/conventional-commits/get-changelog-config.ts
- pnpm-lock.yaml
Support newer version of `conventional-changelog-conventionalcommits`
As per Lerna PR 3873](https://github.com/lerna/lerna/pull/3873)
> new 7.x.x versions of conventional changelog presets use async factory functions createPreset (see https://github.com/conventional-changelog/conventional-changelog/pull/1045)
Fixes
> Using `conventionalcommits` as `changelogPreset` causes lerna version to do nothing
> ```json
> {
>   "changelogPreset": "conventional-changelog-conventionalcommits"
> }
> ```
> 
> Up until the v7 release of conventional-changelog, this worked as expected. After upgrading to v7+, the `lerna version` process exits immediately (with zero exit code) after loading the conventionalcommits package, rather than proceeding with the versioning process.
> fix: support changelog-presets using async factory funcs

- helpers/package.json
- packages/changed/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/exec/package.json
- packages/filter-packages/package.json
- packages/init/package.json
- packages/list/package.json
- packages/listable/package.json
- packages/profiler/package.json
- packages/publish/package.json
- packages/run/package.json
- packages/version/package.json
- packages/watch/package.json
Fixes package types exports inside our unit tests
The latest code change in PR #761 for Types exports seems to have regressed when importing local package in our unit tests within our workspace, this new PR fixes these exports. The helpers also now export the types correctly, I think that one didn't even worked before
> chore(build): update build & TS types exports

- .github/workflows/main.yml
- package.json
- packages/changed/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/exec/package.json
- packages/filter-packages/package.json
- packages/init/package.json
- packages/list/package.json
- packages/listable/package.json
- packages/profiler/package.json
- packages/publish/package.json
- packages/run/package.json
- packages/version/package.json
- packages/watch/package.json
- pnpm-lock.yaml
- tsconfig.base.json
Bump minimum requirement to Node 18
drop Node 16 support since it is EOL
> feat(core)!: upgrade deps to Node 18 and higher

- packages/cli/schemas/lerna-schema.json
- packages/core/src/models/command-options.ts
- packages/version/README.md
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/version-command.ts
Remove deprecated option
The singular option `--skip-bump-only-release` was not representing the fact that it's always used in independent mode and is focusing multiple version releases
> chore(version): remove deprecated singular `--skip-bump-only-release`

- packages/watch/src/watch-command.ts
Saw a PR on Vite project, in which the use of a `Set` removes deduplicate files to watch and makes the chokidar process start faster without watching for duplicate entries
Just implementing the same as Vite's [PR](https://github.com/vitejs/vite/pull/15347) which seems like a good idea to avoid watching duplicate entries and also makes the chokidar watch start faster, it seems like a win-win approach
As per Vite's PR comment
> Vite dev server producing unexpected hmr updates on startup without changes. Chokidar is throttling directory reads on initial watch, producing add events, and vite responds with hmr updates to the add events. Deduping the array passed to `chokidar.watch` on server creation fixes the issue.
> fix(watch): avoid chokidar throttling on watch startup

- package.json
- packages/filter-packages/src/__tests__/get-filtered-packages.spec.ts
- pnpm-lock.yaml
Updating Vitest to latest brought a Vitest error with imported mocked module
We should not import a Vitest module that is mocked in a setup file because that will throw an error as shown below
```sh
FAIL  packages/filter-packages/src/__tests__/get-filtered-packages.spec.ts [ packages/filter-packages/src/__tests__/get-filtered-packages.spec.ts ]
Error: [vitest] Cannot mock "npmlog" because it is already loaded. Did you import it in a setup file?
Please, remove the import if you want static imports to be mocked, or clear module cache by calling "vi.resetModules()" before mocking if you are going to import the file again. See: https://vitest.dev/guide/common-errors.html#cannot-mock-mocked-file.js-because-it-is-already-loaded
❯ packages/filter-packages/src/__tests__/get-filtered-packages.spec. …
```
> chore(tests): remove import of npmlog in test to fix Vitest error

- lerna.json
- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/version/README.md
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/lib/create-release.ts
- packages/version/src/models/index.ts
- packages/version/src/version-command.ts
Provides an alternative to create a GitHub release by letting GitHub automatically generate the name and body for the new release. More info from GitHub docs [Automatically generated release notes](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes)
add a new option `lerna version --generate-release-notes`, closes #793
> feat(version): add `--generate-release-notes` for GitHub release

- package.json
- packages/core/src/utils/collect-updates/__tests__/collect-updates.spec.ts
- packages/core/src/utils/collect-updates/collect-updates.ts
- packages/publish/src/publish-command.ts
running the command `lerna publish --canary --dry-run` shouldn't throw
as pointed out on a blog post, running `lerna publish --canary --dry-run` command was throwing an error with a git ref diff comparing with `undefined^undefined` because the git command was not actually run but only printed to the screen, however we do need to run this command for a proper publish dry-run
> fix(publish): lerna publish --canary --dry-run shouldn't throw

- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/publish-command.ts
This is a continuation of previous PR #801
Running the command `lerna publish --canary --dry-run` shouldn't throw and have valid described tags
This is a continuation of previous PR #801, the output wasn't quite right and wasn't producing a valid version from a SHA, this PR fixes that. 
as pointed out on a blog post, running `lerna publish --canary --dry-run` command was throwing an error with a git ref diff comparing with `undefined^undefined` because the git command was not actually run but only printed to the screen, however we do need to run this command for a proper publish dry-run
It no longer throws an error and the version field is now valid
> fix(publish): --canary --dry-run command should create valid tags

- packages/version/README.md
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/lib/create-release.ts
- packages/version/src/version-command.ts
We should be able to pass `--no-changelog` when executing the new `--generate-release-notes` option, so the full command below should be valid
```sh
lerna version --conventional-commits --no-changelog --create-release github --generate-release-notes
```
Related to issue #793 
Since `--generate-release-notes` is automatically created by GitHub itself, it shouldn't matter if we're not updating our changelog since they are not being used by GitHub to create the release anyway
> GitHub creates a release by automatically generating the name and body for the new release
> fix(version): allow generateReleaseNotes w/o changelog

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/core/src/utils/__tests__/describe-ref.spec.ts
- packages/core/src/utils/collect-updates/collect-updates.ts
- packages/core/src/utils/describe-ref.ts
- packages/version/README.md
- packages/version/src/version-command.ts
Follows original Lerna [PR 3951](https://github.com/lerna/lerna/pull/3951)
> Allows users to customize the tag version separator for independent projects in cases where they do not want to use the default of `@`.
> feat(version): custom tag-version-separator for independent projects

- packages/cli/schemas/lerna-schema.json
- packages/core/src/models/interfaces.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/version-command.ts
We should be able to add `describeTag` from anywhere in the `lerna.json` config, it could be either from the root or the version command.
`lerna.json` root
```json
{
"version": "1.0.0",
"describeTag": "*custom-tag*"
}
```
or `lerna.json` version command
```json
{
"version": "1.0.0",
"command": {
"version": {
"describeTag": "*custom-tag*"
}
}
}
```
As described in Discussion #820 and later confirmed and moved to a new issue #826
Added unit test and also tested manually with VSCode debugger in dry-run mode with `describeTag` set in both root & version command in `lerna.json` and they both detect the option
> fix(version): describeTag in lerna config version cmd/root, fix #826

- package.json
- packages/core/package.json
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package.ts
- packages/init/src/init-command.ts
- packages/publish/package.json
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/__tests__/publish-config-overrides.spec.ts
- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/__tests__/publish-from-package.spec.ts
- packages/publish/src/__tests__/publish-relative-file-specifiers.spec.ts
- packages/publish/src/__tests__/publish-remove-package-fields.spec.ts
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
- packages/version/package.json
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/__tests__/version-conventional-commits.spec.ts
- packages/version/src/__tests__/version-git-hosted-siblings.spec.ts
- packages/version/src/lib/__mocks__/write-package.ts
- pnpm-lock.yaml
The dependency `write-pkg` was renamed to `write-package` and also requires NodeJS 18 which we also require in Lerna-Lite
migrate to newer dependency name since the old `write-pkg` dependency is now deprecated
> chore(deps): upgrade and migrate from `write-pkg` to `write-package`

- packages/version/src/lib/create-release.ts
- packages/version/src/models/index.ts
- packages/version/src/version-command.ts
Follows original Lerna [PR 3979](https://github.com/lerna/lerna/pull/3979)
> After the [8.1.0](https://github.com/lerna/lerna/releases/tag/v8.1.0), the version command does not create a GitHub release when using a custom version seperator. This was because the `createRelease` function had a hard coded `@` in tag name filter.
to fix issue with custom version tag separator not working without `@`
Per Lerna PR
> To test, I create a test repo made changes to a packages and commit them. I then ran:
> 
> ```
> node /tmp/lerna/dist/packages/lerna/dist/cli.js version --tag-version-separator '-' --conventional-commits --create-release github --yes
> ```
> 
> And was able to see the new GitHub release created with the appropriate tag
>
> fix(version): create release when using custom tag-version-separator

- packages/publish/README.md
adding a note in relation to the issue #850
in rare occasion when a publish fails and user is using `--remove-package-fields`, it could leave the `package.json` (of each package) in an invalid state (e.g. `scripts` are now removed). So I'm adding this note to advise users of this limitation
> docs: add note about `--remove-package-fields` when publish fails

- .vscode/launch.json
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/version/README.md
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/conventional-commits/__tests__/__snapshots__/conventional-commits.spec.ts.snap
- packages/version/src/conventional-commits/__tests__/conventional-commits.spec.ts
- packages/version/src/conventional-commits/get-changelog-config.ts
- packages/version/src/conventional-commits/update-changelog.ts
- packages/version/src/models/index.ts
- packages/version/src/version-command.ts
Provide support to `changelogPreset.header`, however we will support `changelogPreset.releaseCommitMessageFormat` because `version.message` does the exact same thing and we will now throw when user tries to configure `changelogPreset.releaseCommitMessageFormat`
Fixes #852
> fix(versions): support `changelogPreset.header`, fixes #852

- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package.ts
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
- packages/version/README.md
- packages/version/src/__tests__/version-command.spec.ts
Peer dependencies that use `workspace:` protocol without enabling `--allow-peer-dependencies-update` are not supported.
Related to issue #869, there is no point in using `workspace:` protocol without enabling `--allow-peer-dependencies-update`, user should either use a fixed version OR allow bumping the peer dependencies
> chore(version): throw when using `workspace:` without allow peer bump

- .vscode/launch.json
- lerna.json
- packages/cli/schemas/lerna-schema.json
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/command.ts
- packages/core/src/models/interfaces.ts
- packages/core/src/package-graph/package-graph.ts
- packages/core/src/package.ts
- packages/core/src/utils/query-graph.ts
- packages/publish/README.md
- packages/publish/src/__tests__/__fixtures__/workspace-protocol-specs/packages/package-5/package.json
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
- packages/publish/src/lib/log-packed.ts
- packages/publish/src/publish-command.ts
- packages/version/README.md
- packages/version/src/version-command.ts
Never publish anything with `workspace:` protocol in their dependencies even with peer dependencies.
fixes #869
- it should never publish any `workspace:` even when `allowPeerDependenciesUpdate` is disabled, `workspace:` are meant to always be bumped since it represent a replacement by the actual version. The main difference other regular dependencies that don't have use `workspace:` will not be bumped without the `allowPeerDependenciesUpdate` flag. So in summary this PR changes the behavior to the following:
- peer deps with `workspace:` protocol will always be bumped
- peer deps with `workspace:` protocol and semver with ranges (e.g. `workspace:>1.0.0 <2.0.0`) will continue to be ignored
- peer deps without `workspace:` will **not** be bumped (same as before)
> fix(publish): always bump & publish peer deps with `workspace:` protocol

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/version/README.md
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
- packages/version/src/version-command.ts
Option to not pass `--ignore-scripts` while updating the lock file after the version bump.
- fixes #877 
- Lerna version should ignore running npm script by default unless the new CLI argument `--run-scripts-on-lockfile-update` is provided. By default, the new behavior is to ignore running the npm scripts when synching lock file after the Lerna version command.
> feat(version): option to not ignore scripts on lock update, fixes #877

- packages/core/src/package-graph/__tests__/package-graph.spec.ts
- packages/core/src/package-graph/package-graph.ts
Introduced logic that transparently handles the patch protocol version syntax by falling back
to the base version string.
https://github.com/lerna-lite/lerna-lite/issues/223
https://yarnpkg.com/cli/patch
Fixes #223
Signed-off-by: Peter Somogyvari <peter.metz@unarin.com>
I have third-party packages in our monorepo that ship with issues that I need to patch in a yarn v4 build setup.
Without this change lerna-lite crashes if we are using it in a project that has any yarn patch protocol usage.
https://github.com/lerna-lite/lerna-lite/issues/223
1. Manually in the repo at https://github.com/hyperledger/cacti
1.1. We made changes to third party dependencies (code in the node_modules folder)
1.2. We committed said changes with `yarn patch`
1.3. The build was broken
1.4. Applied this fix to …
> feat: add support for Yarn patch protocol

- packages/version/src/conventional-commits/__tests__/get-github-commits.spec.ts
- packages/version/src/conventional-commits/get-github-commits.ts
Avoid throwing and failing the versioning
When using `changelogIncludeCommitsClientLogin`, avoid throwing error when last git tag doesn't provide a valid `since` date to query GraphQL, we should just return an empty info and warn the user that the date is invalid (without throwing)
ref, issue #867
> fix(version): don't throw when invalid since date found to query GraphQL

- packages/core/package.json
- packages/core/src/prompt.ts
- pnpm-lock.yaml
Keeping up with the latest dependency releases
inquirer v10 is no longer exporting interfaces (types), so the Renovate PR failed and so this PR is inlining these missing types. It's also mentioned on the inquirer website that the approach Lerna-Lite uses is now the legacy approach and we should eventually move to the new approach (however migrating to this new approach doesn't currently work, so let's keep using the legacy approach for now, I've opened a [Discussion](https://github.com/SBoudrias/Inquirer.js/discussions/1471) for migration help on their github page).
> fix(deps): update dependency inquirer to v10

- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/core/src/models/command-options.ts
- packages/publish/README.md
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/throttle-queue.spec.ts
- packages/publish/src/lib/throttle-queue.ts
- packages/publish/src/publish-command.ts
Follows original Lerna [PR 4013](https://github.com/lerna/lerna/pull/4013)
> This is opened to validate the implementation design and get feedback on the specific values that should be used as defaults.
> 
> Currently known limits when uploading to NPM:
> 
> * Burst limit of 25/500 modules per 24h (depending on account/already-published modules)
> Add three publishing options:
> 
> * `--throttle` to enable/disable throttling
> * `--throttle-size`: the 'bucket size' to use when throttling
> * `--throttle-delay`: Once the bucket is full, the minimum time between the end of a module upload and the start of an other module's upload
> 
> Throttling is enabled by default when publishing to NPM. The throttling implementation is designed to allow changes in the implementation/maintaining …
> feat(publish): enable throttling when publishing modules

- packages/version/src/__tests__/create-release.spec.ts
- packages/version/src/lib/create-release.ts
As per original Lerna [PR 4041](https://github.com/lerna/lerna/pull/4041)
> This pull request introduces the `truncateReleaseBody` function, which ensures that release body content does not exceed the specified maximum length for GitHub and GitLab release descriptions, thereby preventing errors.
As per original Lerna PR
> Fixes Lerna [issue 3833](https://github.com/lerna/lerna/issues/3833)
> fix(version): truncate release body based on maximum size allowed

- eslint.config.mjs
- package.json
- packages/cli/src/cli.ts
- packages/core/src/__tests__/cyclic-package-graph-node.spec.ts
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package-graph/__tests__/package-graph.spec.ts
- packages/core/src/utils/__tests__/collect-uncommitted.spec.ts
- packages/core/src/utils/__tests__/describe-ref.spec.ts
- packages/core/src/utils/__tests__/run-lifecycle.spec.ts
- packages/exec/src/exec-command.ts
- packages/publish/src/__tests__/log-packed.spec.ts
- packages/publish/src/__tests__/npm-dist-tag.spec.ts
- packages/publish/src/__tests__/npm-publish.spec.ts
- packages/run/src/lib/__tests__/npm-run-script.spec.ts
- packages/version/src/__tests__/git-commit.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/__tests__/version-conventional-commits.spec.ts
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/conventional-commits/__tests__/conventional-commits.spec.ts
- pnpm-lock.yaml
`eslint-plugin-node` is deprecated and the alternative `eslint-plugin-n` is actually already a plugin that we use
> chore: remove deprecate eslint-plugin-node and just use n alternative

- packages/core/src/models/command-options.ts
- packages/publish/README.md
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/publish-command.ts
> Add possibility to provide a filepath to the `--summary-file` option in the publish command
As per Lerna's PR 4039 
> This PR introduces a new capability to the Lerna library, allowing users to specify a filepath instead of a directory path for the `--summary-file` option.
> 
> Previously, users could only provide a directory path and the created filename is statically defined in the code as `lerna-publish-summary.json` , which limited the flexibility in defining the location and name of the summary file.
As per Lerna's PR
> With this change, users can now directly specify the full path, including the filename, where the summary should be saved.
> In the `publish-command.spec.ts` file, adding a new test case where a filepath is passed as input parameter.
> feat(publish): support full file path for --summary-file

- packages/core/src/models/command-options.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/lib/git-commit.ts
- packages/version/src/models/index.ts
- packages/version/src/version-command.ts
As per Lerna's PR 3954
> allows overriding of the commit message
> fixes Lerna's issue 3936
> Using "--amend" and "--message" options will not overwrite the original commit message
> fix(version): enable changing commit message when using amend

- packages/core/src/command.ts
Replicate a fix that was provided as a patch in [yeoman-api](https://github.com/yeoman/yeoman-api) in this patch [commit](https://github.com/yeoman/yeoman-api/commit/29061293f6681b094f9205c897595ab4255fc76e). This fix was described as the following: 
> `@yeoman/api` packages is a base definition for every other workspace, it provides:
> 
> * immutable types that should never have breaking changes.
> * stable base dependencies using peerDependencies.
> 
> A new release `@yeoman/api` should be individual without touching other packages. `@lerna-lite` commands are (eg: `lerna publish --ignore-changes '**' --force-publish @yeoman/types`):
> 
> * touching projects with widened peerDependencies, as far as I remember it adds devDependencies:
> …
> fix(core): don't include other deps when `graphType` is provided

- package.json
- packages/publish/package.json
- packages/publish/src/publish-command.ts
- pnpm-lock.yaml
- scripts/cleanup-temp-files.mjs
Replace 2 places that use `node-glob` with `globby` since we use it across the project
simply want to decrease number of dependencies :)
I eventually want to migrate to `tinyglobby` but not until they support the missing option `followSymbolicLinks`
tested locally by running `cleanup-temp-files.mjs` npm script which runs after unit tests closes. While investigating, I found that `{ onlyDirectories: true }` is required for the migration to work
> fix: replace node-glob with globby to decrease deps

- packages/npmlog/package.json
- packages/npmlog/src/gauge/wide-truncate.ts
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- pnpm-lock.yaml
replace `strip-ansi` import with `stripVTControlCharacters` from `node:util` native
References https://github.com/es-tooling/ecosystem-cleanup/issues/122
existing tests
> fix: drop `strip-ansi` in favor of native stripVTControlCharacters

- packages/core/src/__tests__/command.spec.ts
- packages/core/src/utils/__tests__/env-replace.spec.ts
- packages/core/src/utils/__tests__/pulse-till-done.spec.ts
Vitest `toThrowError` shouldn't be set to an empty string
fixes an issue identified in latest vitest-ecosystem-ci
https://github.com/vitest-dev/vitest-ecosystem-ci/actions/runs/11397873060/job/31714024446
> chore: fix test failures found in vitest-ecosystem-ci

- packages/list/README.md
ndjson.org domain expired and has been taken over by a website with malware. This update will use the official ndjson spec readme.
Discussion: https://github.com/ndjson/ndjson.github.io/issues/24
> Domain ndjson.org has expired
> Looks like the website now contains malware.
> docs: use ndjson spec link instead of ndjson.org

- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/version-command.ts
Skip certain conditions in dry-run mode
fixes #988 
No need to throw in dry-run mode when user has a release without changelog enabled
> fix: dry-run, don't throw no changelog w/o release, fixes #988

- packages/core/src/filter-packages/__tests__/get-filtered-packages.spec.ts
- packages/core/src/project/project.ts
As per Lerna's PR 4159
> cosmiconfig have been upgrade to 9.0.0 in #4062 But there is a breaking change in cosmiconfig 9.0.0 See https://github.com/cosmiconfig/cosmiconfig/blob/main/CHANGELOG.md#900
> 
> > Breaking change: This is the default value if you don't pass a stopDir option, which means that cosmiconfig no longer traverses directories by default, and instead just looks in the current working directory.
> > If you want to achieve maximum backwards compatibility without adding an explicit stopDir, add the searchStrategy: 'global' option.
> 
> Any lerna commands run in subdirectories are broken now.
Fixes issue opened in Lerna, [issue 4118](https://github.com/lerna/lerna/issues/4118)
> Lerna seems to be losing --scope directory context
> This is due to the cosmiconfig upgrade …
> fix: use cosmiconfig global searchStrategy to fix breaking behaviour

- packages/core/src/__tests__/package.spec.ts
- packages/publish/README.md
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/publish-command.ts
Instead of using plus (+) sign in package name provided by --canary flag, use dot.
This PR is based on original Lerna's PR 4124
It's not possible to publish --canary version into jfrog artifactory, as jfrog is cutting part of filename, due to + (plus) character. So, instead of using +, I would suggest to use dot.
https://github.com/lerna/lerna/issues/2060
As per Lerna's original author [comment](https://github.com/lerna/lerna/issues/2060#issuecomment-569968758)
> Yeah, in retrospect using the `+` to append `commit_hash` was a mistake, as even the public registry completely ignores it (it's allowed to, per the [spec](https://semver.org/#spec-item-10)).
> Yes, true, the spec is only speaking to precedence there. In my manual testing, I found that attempting to publish version …
> fix(publish): replace +{SHA} with .{SHA} in lerna publish --canary

- packages/version/package.json
- pnpm-lock.yaml
Remove deprecated and unnecessary dev dependency `@types/git-url-parse`
> chore: remove unnecessary deprecated @types/git-url-parse

- packages/core/src/package-graph/package-graph.ts
- packages/core/src/utils/collect-updates/__tests__/collect-updates.spec.ts
- packages/core/src/utils/collect-updates/__tests__/lib-make-diff-predicate.spec.ts
- packages/core/src/utils/collect-updates/collect-updates.ts
- packages/core/src/utils/collect-updates/lib/make-diff-predicate.ts
- packages/publish/README.md
When dependencies in pnpm `catalog:` changes, it should detect that there was a change in that package and a version bump is required for that package (even when dep with `catalog:` text itself never changed, so we need a way to track that the catalog dep version changed and we advise the package that something changed and it requires a package version bump when running `lerna version`)
fixes #1010 (partially, since local peer deps will not be supported)
The beauty about pnpm `catalog:` is that we can simply replace any packages that use multiple dependencies across the monorepo and have 1 central place to control which version to use across the entire solution (ie: installing VueJS in multiple packages but use the exact same version everywhere) which is great but.... this however brings …
> fix(version): pnpm catalog changes should be reflected in packages

- .vscode/launch.json
- helpers/fixtures.ts
- helpers/git/index.ts
- package.json
- packages/version/README.md
- packages/version/package.json
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/config-builder-preset.ts
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/erroring-preset.ts
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/legacy-callback-preset.ts
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/local-preset-async.ts
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/local-preset.ts
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/null-preset.ts
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/writer-opts.ts
- packages/version/src/conventional-commits/__tests__/__snapshots__/conventional-commits.spec.ts.snap
- packages/version/src/conventional-commits/__tests__/conventional-commits.spec.ts
- packages/version/src/conventional-commits/get-changelog-config.ts
- packages/version/src/conventional-commits/recommend-version.ts
- packages/version/src/conventional-commits/update-changelog.ts
- packages/version/src/conventional-commits/writer-opts-transform.ts
- packages/version/src/interfaces.ts
- pnpm-lock.yaml
Upgrade 2 conventional-changelog packages to their latest major
- `conventional-changelog@7`
- `conventional-changelog-conventionalcommits@9`
These 2 dependencies had again major breaking changes that required some major changes to get them working (also as usual, no migration guide provided, so it's a lot of code reading to figure out how to migrate). It seems ok now but one of the biggest difference now is that the new API for Presets only seems to accept an object like this `{ parser, writer, whatBump }`  (in other words, `parserOpts`, `writerOpts` were renamed and I've put some code to support them until our next major, even though I don't think anyone uses this super old legacy loading of "Preset as a file config")
> feat: upgrade `conventional-changelog` to v7

- __fixtures__/pack-directory/packages/a/prepare.ts
- packages/version/README.md
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
Remove unused code
Forgot to remove this check when releasing the latest major, we no longer need to check the NPM version to be >=8.5.0 since NodeJS 20.17 (our new requirement) has NPM 10.8.2 by default so the version becomes irrelevant
> refactor: remove unnecessary NPM version check lower than 8.5

- packages/version/src/conventional-commits/make-bump-only-filter.ts
- packages/version/src/conventional-commits/update-changelog.ts
Simplifying code
Another small refactor to make the `makeBumpOnlyFilter` do only 1 call instead of 2
> refactor: simplify `makeBumpOnlyFilter` to make only 1 call instead of 2

- packages/core/src/corepack/__tests__/exec-package-manager.spec.ts
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/git-clients/__tests__/github-client.spec.ts
avoid clearing `process.env = {}` since that cancels temp dir creation with `tmpdir()` or `process.env.TEMP`
`tmpdir()` was returning `undefined` on Windows platform but was working in Ubuntu (CI), the issue was caused by the clearing of `process.env` making the `tmpdir()` unusable
> chore: avoid clearing the entire process.env in tests

- packages/core/package.json
- packages/version/package.json
- pnpm-lock.yaml
The migration to zeptomatch in previous PR #1074 incorrectly installed it as `devDependencies` when it should really be installed as `dependencies`
fixes #1076
previous unit tests are fine
> fix: zeptomatch should be installed as dep not devDeps, fixes #1076

- packages/version/README.md
Hey maintainers,
I ran into an issue where the `version` command behaves unexpectedly when using the `--force-publish` flag with a specific version number. I've corrected the documentation to prevent confusion for other users.
**The Problem**
When running a command like `lerna version --force-publish <version>`, for example:
```bash
lerna version --force-publish 4.9.3
```
Lerna-lite misinterprets `4.9.3` as a package name to be force-published, not as the target version. This results in the following warning and subsequent failure, as no changed packages are found:
```
lerna-lite WARN force-publish 4.9.3
lerna-lite success No changed packages to version
```
**The Solution**
The correct syntax is to provide the version number as the primary argument to `lerna version` and then use a glob …
> docs: correct documentation for --force-publish flag usage

- packages/npmlog/package.json
- packages/npmlog/src/gauge/progress-bar.ts
- packages/npmlog/src/gauge/template-item.ts
- packages/npmlog/src/gauge/wide-truncate.ts
- pnpm-lock.yaml
replace `string-width` with a smaller alternative `fast-string-width` in our `npmlog` inline package
`fast-string-width` has a [pkg-size](https://pkg-size.dev/fast-string-width) of 15Kb with only has 2 dependencies and `string-width` has a [pkg-size](https://pkg-size.dev/string-width) of 65Kb with 5 dependencies. 
This change was suggested by the e18e initiative to lower package size
https://github.com/e18e/ecosystem-issues/issues/194
> fix(deps): replace `string-width` with `fast-string-width`

- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package.ts
- packages/publish/src/publish-command.ts
Anytime a dependency that has `catalog:` protocol is found, it should be replaced with the correct semver range found in the global catalog. 
I found that using `npm-package-arg` wasn't always finding all dependencies that have `catalog:` protocols and by such in some rare occasions a couple of catalog semver range remained. This only happened on packages that had catalog on the same dependency name in multiple dependency types (e.g. dependency `"react": "catalog:"` found in 3 different categories like `dependencies`, `devDependencies` and `peerDependencies`)
> fix: all dependencies with Catalog protocol should be replaced

- eslint.config.mjs
Replace a simple typescript-eslint config with newer approach
Just migrate a typescript-eslint config call to the newer approach since the previous approach was tagged as deprecated, see
https://typescript-eslint.io/packages/typescript-eslint/#config-deprecated
> chore: replace deprecated typescript-eslint config fn

- packages/core/src/package-graph/__tests__/package-graph.spec.ts
- packages/core/src/package-graph/package-graph.ts
- packages/core/src/utils/catalog-utils.ts
The `pnpm catalog` implementation only looks at catalog when dependency versions are set to `catalog:` or `catalog:default`.
However when using named catalog, `default` catalog can either be `catalog` or `catalogs.default`
In this PR I fallback to `catalogs.default[depName]` when catalog doesn't contain the expected version.
We currently use a patched version of lerna `@lerna-lite/core@4.4.1` with this change in production, and I added a few unit tests.
> fix: supports catalogs.default

- .vscode/launch.json
- package.json
- packages/core/src/filter-packages/lib/filter-packages.ts
- packages/npmlog/package.json
- packages/npmlog/src/__tests__/npmlog-basic.spec.ts
- packages/npmlog/src/__tests__/npmlog-progress.spec.ts
- packages/npmlog/src/gauge/__tests__/index.spec.ts
- packages/npmlog/src/gauge/__tests__/plumbing.spec.ts
- packages/npmlog/src/gauge/has-color.ts
- packages/npmlog/src/gauge/plumbing.ts
- packages/npmlog/src/gauge/themes.ts
- packages/npmlog/src/npmlog.ts
- pnpm-lock.yaml
- vitest/vitest.color.config.ts
in the npmlog package, we can replace `console-control-strings` and `color-support` with `tinyrainbow` (a fork of `picocolors`) which we already use in the core package and everywhere else
We already use `tinyrainbow` in the core file and it's much smaller than these other 2 dependencies that are only used in npmlog package, so let's do the migration to use less and smaller deps. Since we already use `tinyrainbow` in the core, then this would pretty much mean that we would drop the equivalent of 2 dependencies.
Also in the next major version, we'll completely drop `tinyrainbow` and go with native code `util.styleText()` and so this is a good preparation towards that goal
> fix(deps): replace console-control-strings/color-support w/tinyrainbow in npmlog

- packages/version/src/conventional-commits/__tests__/__snapshots__/conventional-commits.spec.ts.snap
- packages/version/src/conventional-commits/__tests__/conventional-commits.spec.ts
remove test flakiness from conventional-changelog test file
update the test to remove flakiness (it rarely failed remotely, though it does sometime, however it nearly always failed locally), with this code update the test with snapshot will pass with either an h1 or an h2 `# 1.1.0 (YYYY-MM-DD)` or `## 1.1.0 (YYYY-MM-DD)`
> chore(tests): remove test flakiness by updating test
