- .eslintrc
- .vscode/launch.json
- packages/core/src/command.ts
- packages/core/src/git-clients/github-client.ts
- packages/version/src/lib/create-release.ts
- packages/version/src/lib/update-lockfile-version.ts
- packages/version/src/versionCommand.ts
- roller.json
- previous code only worked with npm lock file version 1, this new code will work for both version 1 (legacy) & 2 (newer)
> fix(version): should update npm root lock file when lockfileVersion>=2

- packages/version/src/lib/git-push.ts
- ref Lerna fix [#3005](https://github.com/lerna/lerna/pull/3005)
- also add missing types
> fix(version): fix overall exit code of 128 if git push --atomic fails

- packages/core/src/package-graph/package-graph.ts
- ref Lerna enhancement [#2874](https://github.com/lerna/lerna/pull/2874)
> feat(core): drastically reduce time taken to check for cycles

- packages/version/src/lib/git-push.ts
- ref Lerna PR [#2696](https://github.com/lerna/lerna/pull/2696)
> fix(version): better non-atomic push fallback condition

- packages/publish/src/publishCommand.ts
- ref Lerna PR [#2931](https://github.com/lerna/lerna/pull/2931)
> chore(publish): improve notice message for from-git

- packages/version/src/lib/update-lockfile-version.ts
- ref Lerna PR [#2914](https://github.com/lerna/lerna/pull/2914)
> fix(publish): add version bump in a lockfile v2 format

- packages/cli/src/versionCommandOptions.ts
- packages/version/README.md
- packages/version/src/lib/git-commit.ts
- packages/version/src/versionCommand.ts
- ref Lerna PR [#2897](https://github.com/lerna/lerna/pull/2897)
> feat(version): add `--signoff` git flag

- packages/publish/README.md
- packages/publish/src/publishCommand.ts
- ref, Lerna PR [#2859](https://github.com/lerna/lerna/pull/2859)
> chore(publish): add catch error for verifyWorkingTree

- packages/run/src/runCommand.ts
- ref Lerna PR [#2974](https://github.com/lerna/lerna/pull/2974)
> feat(run): Improve output with `--no-bail`

- package-lock.json
- packages/core/package.json
- packages/core/src/__mocks__/prompt.js
- packages/core/src/__tests__/otplease.spec.ts
- packages/core/src/otplease.ts
- packages/core/src/prompt.ts
- packages/publish/src/publishCommand.ts
- packages/version/src/lib/prompt-version.ts
- packages/version/src/versionCommand.ts
- Lerna original code had non-strict code on null/undefined while it was strict in this lib, this commit fixes this
> fix(core): OTP please  method had non-strict code

- package-lock.json
- packages/core/package.json
- packages/publish/package.json
> fix(deps): move ts-node to devDependencies

- packages/run/README.md
- packages/run/src/lib/__tests__/npm-run-script.spec.ts
- packages/run/src/lib/get-npm-exec-opts.ts
- ref Lerna PR [#3107](https://github.com/lerna/lerna/pull/3107)
> feat(run): add `LERNA_PACKAGE_NAME` env var to `run` command

- packages/version/src/version-command.ts
Fixes #146.
Ideally, a corresponding test should also be added, but I don't have enough knowledge about the internals and how tests are written for lerna-lite to be able to write such a test myself.
> fix(version): include the updated root package-lock.json file in commits

- .vscode/launch.json
- packages/run/src/run-command.ts
> fix(run): display pkg name only when not streaming, fixes #149

- README.md
- package-lock.json
- package.json
- packages/cli/src/cli-commands/cli-init-commands.ts
- packages/cli/src/lerna-entry.ts
- packages/core/src/command.ts
- packages/core/src/models/index.ts
- packages/init/README.md
- packages/init/package.json
- packages/init/src/__tests__/__fixtures__/has-lerna/lerna.json
- packages/init/src/__tests__/__fixtures__/has-package/package.json
- packages/init/src/__tests__/__fixtures__/updates/lerna.json
- packages/init/src/__tests__/__fixtures__/updates/package.json
- packages/init/src/__tests__/init-command.spec.ts
- packages/init/src/index.ts
- packages/init/src/init-command.ts
- packages/init/tsconfig.bundle.json
- this can be useful for new user of the lib
> feat(init): add Lerna `init` command to get started

- .github/renovate.json5
test Renovate integration
test Renovate integration
> chore: remove Renovate schedule to make sure it works

- packages/cli/src/cli-commands/cli-run-commands.ts
- packages/core/src/models/command-options.ts
- packages/run/README.md
- packages/run/src/__fixtures__/powered-by-nx/nx.json
- packages/run/src/__fixtures__/powered-by-nx/packages/package-4/package.json
- packages/run/src/__tests__/run-command.spec.ts
- packages/run/src/run-command.ts
- replicate Lerna's [PR 3155](https://github.com/lerna/lerna/pull/3155)
stay up to date with original Lerna
> bugfix(run): Nx integration edge cases

- packages/core/src/models/interfaces.ts
- packages/init/src/__tests__/init-command.spec.ts
- packages/init/src/init-command.ts
- packages/run/src/run-command.ts
keep in sync with original Lerna
follows Lerna's PR [3182](https://github.com/lerna/lerna/pull/3182)
> fix(run): Nx correctly detect if target dependencies default are set

- .eslintrc.json
- packages/exec/src/__tests__/exec-command.spec.ts
- packages/publish/src/__tests__/publish-canary.test.js
- packages/publish/src/__tests__/publish-command.test.js
- packages/publish/src/__tests__/publish-from-git.test.js
- packages/publish/src/__tests__/publish-from-package.test.js
- packages/publish/src/__tests__/publish-licenses.spec.ts
- packages/publish/src/__tests__/publish-relative-file-specifiers.test.js
- packages/publish/src/__tests__/publish-tagging.test.js
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.test.js
- packages/version/src/__tests__/version-allow-branch.spec.ts
- packages/version/src/__tests__/version-bump-prerelease.spec.ts
- packages/version/src/__tests__/version-bump.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/__tests__/version-conventional-commits.spec.ts
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/__tests__/version-git-hosted-siblings.spec.ts
- packages/version/src/__tests__/version-ignore-changes.spec.ts
- packages/version/src/__tests__/version-include-merged-tags.spec.ts
- packages/version/src/__tests__/version-lifecycle-scripts.spec.ts
- packages/version/src/__tests__/version-message.spec.ts
> tests: add CLI positional argument on necessary commands

- packages/publish/src/__tests__/publish-canary.test.js
> tests: add more publish unit tests

- packages/changed/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/exec/package.json
- packages/exec/src/__tests__/exec-command.spec.ts
- packages/init/package.json
- packages/list/package.json
- packages/publish/package.json
- packages/run/package.json
- packages/version/package.json
- pnpm-lock.yaml
add more unit tests and also add missing dev deps since we now use pnpm which doesn't hoist by default
> chore: add more `exec` unit tests

- packages/cli/src/cli-commands/__tests__/cli-diff-commands.spec.ts
- packages/cli/src/cli-commands/cli-diff-commands.ts
- packages/diff/package.json
- pnpm-lock.yaml
add missing dependency from `diff` command, also add stack error to console error
running `lerna diff` in some occasion was throwing an error of a missing dependency
> fix(diff): add `diff` command missing dependency

- packages/core/src/package.ts
- packages/version/src/lib/update-lockfile-version.ts
improve code
avoid possible runtime failure by making sure all string `,match()` returns an array
> fix(version): make sure we always have regex match array

- packages/core/src/utils/run-lifecycle.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
> tests: fix failing unit tests

- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/conventional-commits/__tests__/conventional-commits.spec.ts
- packages/core/src/conventional-commits/update-changelog.ts
- packages/core/src/models/command-options.ts
- packages/core/src/models/interfaces.ts
- packages/version/README.md
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/version-command.ts
Since we now have 2 changelog include options, we should use better name to identify both, the new list is
- `--changelog-include-commits-git-author` previously named as _`--changelog-include-commit-author-fullname`_
- `--changelog-include-commits-client-login`
Simplify `lerna version` option names, use a better option names to make them easier to understand
> fix(version): rename option to `--changelog-include-commits-git-author`

- packages/core/src/git-clients/__tests__/github-client.spec.ts
unit test issue was identified in Lerna [PR 3152](https://github.com/lerna/lerna/pull/3152)
don't use real local .env file to execute unit tests
> tests: fix github-client tests to not use real env

- __fixtures__/pack-directory/packages/a/package.json
- __fixtures__/pack-directory/packages/a/src/index.ts
- __fixtures__/pack-directory/packages/b/package.json
- __fixtures__/pack-directory/packages/c/package.json
- __fixtures__/pack-directory/packages/d/index.ts
- __fixtures__/pack-directory/packages/d/package.json
- __fixtures__/pack-directory/packages/d/postpack.ts
- packages/core/src/utils/__tests__/collect-uncommitted.spec.ts
- packages/publish/src/lib/__mocks__/get-npm-username.js
- packages/publish/src/lib/__mocks__/get-npm-username.ts
- packages/publish/src/lib/__mocks__/get-packages-without-license.js
- packages/publish/src/lib/__mocks__/get-packages-without-license.ts
- packages/publish/src/lib/__mocks__/get-two-factor-auth-required.js
- packages/publish/src/lib/__mocks__/get-two-factor-auth-required.ts
- packages/publish/src/lib/__mocks__/get-unpublished-packages.js
- packages/publish/src/lib/__mocks__/get-unpublished-packages.ts
- packages/publish/src/lib/__mocks__/npm-dist-tag.js
- packages/publish/src/lib/__mocks__/npm-dist-tag.ts
- packages/publish/src/lib/__mocks__/pack-directory.ts
- packages/publish/src/lib/__mocks__/verify-npm-package-access.js
- packages/publish/src/lib/__mocks__/verify-npm-package-access.ts
Part 2 of converting more JS to TS and also migrate more `require()` to `import`
in preparation to be full ESM
> chore: convert more JS to TS files and change require() to imports

- helpers/cli.ts
- helpers/serializers/serialize-placeholders.ts
- packages/cli/package.json
- packages/cli/src/lerna-entry.ts
- packages/core/src/command.ts
- packages/diff/src/__tests__/diff-command.spec.ts
- packages/init/src/__tests__/init-command.spec.ts
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/version/src/__tests__/version-lifecycle-scripts.spec.ts
- pnpm-lock.yaml
migrate few more `require()` to `import`
in preparation to be full ESM
> chore: migrate few require() to imports as ESM

- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/publish-lifecycle-scripts.spec.ts
add more unit test
increase publish command unit test coverage
> tests: add more publish command unit tests

- packages/run/src/run-command.ts
replicate Lerna [PR 3277](https://github.com/lerna/lerna/pull/3277)
stay in sync with Lerna
> fix(run): do not toposort when running in parallel with useNx to match legacy

- packages/publish/src/__tests__/publish-command.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
small tweak to see if that improves test coverage
> tests: tweak some unit tests

- packages/core/src/conventional-commits/writer-opts-transform.ts
> fix(version): changelog client login not need  linkRefs in template

- packages/core/src/conventional-commits/get-commits-since-last-release.ts
> chore: add more logs when finding oldest commit since last tag

- packages/run/package.json
- pnpm-lock.yaml
forgot to upgrade jest-circus when creating previous PR to upgrade Jest v29
> chore(deps): update jest-circus to v29

- package.json
- packages/core/package.json
- packages/publish/package.json
- pnpm-lock.yaml
> chore(deps): update dependencies which fails with renovate

- packages/cli/package.json
- packages/cli/src/lerna-entry.ts
- pnpm-lock.yaml
add missing TS Type to fix build error 
fix build error since last recent TypeScript update
> chore(cli): add missing Type to fix TSC build error

- .github/workflows/main.yml
- packages/changed/tsconfig.bundle.json
- packages/cli/tsconfig.bundle.json
- packages/core/src/git-clients/GitLabClient.ts
- packages/core/src/models/interfaces.ts
- packages/core/tsconfig.bundle.json
- packages/diff/tsconfig.bundle.json
- packages/exec/tsconfig.bundle.json
- packages/info/tsconfig.bundle.json
- packages/init/tsconfig.bundle.json
- packages/list/tsconfig.bundle.json
- packages/listable/tsconfig.bundle.json
- packages/optional-cmd-common/tsconfig.bundle.json
- packages/publish/tsconfig.bundle.json
- packages/run/tsconfig.bundle.json
- packages/version/src/lib/create-release.ts
- packages/version/src/lib/get-current-branch.ts
- packages/version/src/lib/git-add.ts
- packages/version/src/lib/git-commit.ts
- packages/version/src/lib/git-tag.ts
- packages/version/src/lib/is-anything-committed.ts
- packages/version/src/lib/is-behind-upstream.ts
- packages/version/src/lib/remote-branch-exists.ts
- packages/version/src/types/index.ts
- packages/version/src/version-command.ts
- packages/version/tsconfig.bundle.json
TypeScript and build related stuff
Add more TypeScript Types and cleanup `tsconfig.json` files
> chore: add more TS Types and cleanup tsconfig files

- packages/cli/package.json
- packages/cli/src/lerna-entry.ts
- pnpm-lock.yaml
remove unnecessary dependency
we could go without `type-fest` to reduce dependencies
> chore(deps): remove type-fest dependency

- packages/core/src/__tests__/child-process.spec.ts
- packages/core/src/child-process.ts
- packages/exec/package.json
- packages/exec/src/__tests__/exec-command.spec.ts
- packages/exec/src/exec-command.ts
- packages/publish/package.json
- packages/publish/src/__tests__/log-packed.spec.ts
- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/__tests__/publish-from-package.spec.ts
- packages/publish/src/lib/log-packed.ts
- packages/publish/src/publish-command.ts
- packages/run/package.json
- packages/run/src/__tests__/run-command.spec.ts
- packages/run/src/run-command.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/lib/create-release.ts
- packages/version/src/version-command.ts
- pnpm-lock.yaml
improve `dry-run` styling by adding `chalk` color
just to improve dry-run logging readability
> chore: improve dry-run styling by adding chalk color

- packages/core/src/command.ts
- packages/core/src/models/interfaces.ts
- packages/diff/src/diff-command.ts
- packages/exec/src/exec-command.ts
- packages/list/src/list-command.ts
- packages/publish/src/__tests__/publish-licenses.spec.ts
- packages/publish/src/__tests__/publish-lifecycle-scripts.spec.ts
- packages/publish/src/__tests__/publish-relative-file-specifiers.spec.ts
- packages/publish/src/__tests__/publish-tagging.spec.ts
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
- packages/publish/src/publish-command.ts
- packages/run/src/run-command.ts
- packages/version/src/__tests__/version-allow-branch.spec.ts
- packages/version/src/__tests__/version-bump-prerelease.spec.ts
- packages/version/src/__tests__/version-bump.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/__tests__/version-conventional-commits.spec.ts
- packages/version/src/__tests__/version-git-hosted-siblings.spec.ts
- packages/version/src/__tests__/version-ignore-changes.spec.ts
- packages/version/src/__tests__/version-include-merged-tags.spec.ts
- packages/version/src/__tests__/version-lifecycle-scripts.spec.ts
- packages/version/src/__tests__/version-message.spec.ts
- packages/version/src/version-command.ts
adding more TypeScript types
adding more TypeScript types
> chore: add more TypeScript Types in all Commands

- packages/diff/src/__tests__/diff-command.spec.ts
- packages/exec/src/__tests__/exec-command.spec.ts
- packages/info/src/__tests__/info-command.spec.ts
- packages/list/src/__tests__/list-command.spec.ts
- packages/listable/src/__tests__/listable-format.spec.ts
- packages/optional-cmd-common/src/lib/__tests__/get-filtered-packages.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/__tests__/publish-from-package.spec.ts
- packages/publish/src/__tests__/publish-licenses.spec.ts
- packages/publish/src/__tests__/publish-lifecycle-scripts.spec.ts
- packages/publish/src/__tests__/publish-relative-file-specifiers.spec.ts
- packages/publish/src/__tests__/publish-tagging.spec.ts
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
- packages/run/src/__tests__/run-command.spec.ts
- packages/version/src/__tests__/version-allow-branch.spec.ts
- packages/version/src/__tests__/version-bump-prerelease.spec.ts
- packages/version/src/__tests__/version-bump.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/__tests__/version-conventional-commits.spec.ts
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/__tests__/version-git-hosted-siblings.spec.ts
- packages/version/src/__tests__/version-ignore-changes.spec.ts
- packages/version/src/__tests__/version-include-merged-tags.spec.ts
- packages/version/src/__tests__/version-lifecycle-scripts.spec.ts
- packages/version/src/__tests__/version-message.spec.ts
add more unit coverage by using Command class directly
> tests: add more unit test coverage and types

- packages/diff/src/__tests__/diff-command.spec.ts
- packages/exec/src/__tests__/exec-command.spec.ts
- packages/info/src/__tests__/info-command.spec.ts
- packages/list/src/__tests__/list-command.spec.ts
- packages/listable/src/__tests__/listable-format.spec.ts
- packages/optional-cmd-common/src/lib/__tests__/get-filtered-packages.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/__tests__/publish-from-package.spec.ts
- packages/publish/src/__tests__/publish-licenses.spec.ts
- packages/publish/src/__tests__/publish-lifecycle-scripts.spec.ts
- packages/publish/src/__tests__/publish-relative-file-specifiers.spec.ts
- packages/publish/src/__tests__/publish-tagging.spec.ts
- packages/publish/src/__tests__/publish-workspace-protocol-specifiers.spec.ts
- packages/run/src/__tests__/run-command.spec.ts
- packages/version/src/__tests__/version-allow-branch.spec.ts
- packages/version/src/__tests__/version-bump-prerelease.spec.ts
- packages/version/src/__tests__/version-bump.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/__tests__/version-conventional-commits.spec.ts
- packages/version/src/__tests__/version-create-release.spec.ts
- packages/version/src/__tests__/version-git-hosted-siblings.spec.ts
- packages/version/src/__tests__/version-ignore-changes.spec.ts
- packages/version/src/__tests__/version-include-merged-tags.spec.ts
- packages/version/src/__tests__/version-lifecycle-scripts.spec.ts
- packages/version/src/__tests__/version-message.spec.ts
> tests: increase unit test coverage for Conf class

- packages/cli/src/__tests__/cli.spec.ts
- packages/run/src/__tests__/run-command.spec.ts
unit tests
add more unit test coverage
> tests: add more CLI and Run command unit test coverage

- packages/optional-cmd-common/src/__tests__/index.spec.ts
- packages/optional-cmd-common/src/lib/__tests__/get-filtered-packages.spec.ts
unit tests for the `optional-cmd-command` package
add more unit tests coverage
> tests: add more unit tests to cover filtered-package methods

- packages/diff/src/__tests__/lib/get-last-commit.spec.ts
add unit tests
full Diff command unit tests coverage
> tests: add full Diff command unit tests coverage

- packages/run/src/__tests__/run-command.spec.ts
- packages/run/src/run-command.ts
remove invalid Lerna 6 links that are now invalid anyway
> chore(run): remove invalid lerna 6 links

- packages/watch/src/watch-command.ts
Add log when all watch commands are completed
Add log when all watch commands are completed
> chore(watch): show log when all watch callbacks are completed

- package.json
- pnpm-lock.yaml
Seems like `json5` dependency has a vulnerability used by ESLint (dev dependency)
ran pnpm audit to fix dev dependency vulnerability
> chore(deps): run pnpm audit to fix json5 vulnerability in ESLint

- packages/core/package.json
- packages/core/src/project/lib/apply-extends.ts
- pnpm-lock.yaml
Remove `require()` code in order to eventually move to ESM
in preparation to support full ESM
> chore(core): replace require() with code that works as ESM

- package.json
- packages/filter-packages/package.json
- packages/profiler/package.json
- packages/publish/package.json
- pnpm-lock.yaml
Manually update some dependencies identified by Renovate PR #499
Run a manual update of dependencies to keep only [cosmiconfig](https://togithub.com/cosmiconfig/cosmiconfig) deps in that PR #499 which is causing unit tests to fail
> fix(deps): update all non-major dependencies

- .github/renovate.json5
- packages/core/package.json
- pnpm-lock.yaml
Temporary use a fixed version of `cosmiconfig` 
Use a fixed of version of `cosmiconfig` (v8.0.0) to avoid unit test failures that came up in PR #499 which caused regression.
> chore(deps): use a fixed version 8.0.0 of cosmiconfig to avoid test fail

- packages/cli/src/cli-commands/cli-version-commands.ts
Add `--exclude-dependents` to `lerna version` CLI
adding the option to the version CLI might not do anything but is only added to see if it helps with this [post](https://github.com/lerna-lite/lerna-lite/issues/491#issuecomment-1452231018)
> chore(version): add --exclude-dependents to version CLI command

- package.json
- tsconfig.base.json
> chore(build): tweak project tsconfig base options

- packages/watch/src/watch-command.ts
Update `lerna watch` exit code
As per NodeJS docs. Signal Exits: If Node.js receives a fatal signal such as `SIGINT` or `SIGTERM`, then its exit code will be `128` plus the value of the signal code. This is a standard POSIX practice, since exit codes are defined to be 7-bit integers, and signal exits set the high-order bit, and then contain the value of the signal code.
> chore(watch): watch exit signal code should be over 128

- packages/core/src/utils/defaults.ts
- packages/core/src/utils/npm-conf.ts
Get ready for ESM support
Replace any `exports` code with ES6/ESM format
> chore(core): replace defaults exports to ES6 Class

- .github/renovate.json5
- .github/workflows/main.yml
- package.json
- pnpm-lock.yaml
downgrade pnpm to v7
tried to upgrade to pnpm v8 but it requires Node 16, so let's wait until our next major 2.0
> chore(deps): downgrade pnpm to v7

- packages/core/src/package-graph/__tests__/__snapshots__/package-graph.spec.ts.snap
- packages/core/src/utils/collect-updates/__tests__/lib-collect-packages.spec.ts
- packages/publish/src/__tests__/get-unpublished-packages.spec.ts
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/publish-licenses.spec.ts
- packages/publish/src/__tests__/publish-tagging.spec.ts
- packages/run/src/__tests__/__snapshots__/run-command.spec.ts.snap
- packages/run/src/__tests__/run-command.spec.ts
- packages/version/src/__tests__/__snapshots__/update-lockfile-version.spec.ts.snap
- packages/version/src/__tests__/__snapshots__/version-build-metadata.spec.ts.snap
- packages/version/src/__tests__/__snapshots__/version-command.spec.ts.snap
- packages/version/src/__tests__/__snapshots__/version-conventional-commits.spec.ts.snap
- packages/version/src/__tests__/__snapshots__/version-ignore-changes.spec.ts.snap
- packages/version/src/conventional-commits/__tests__/conventional-commits.spec.ts
This PR is a quick **temporary** to an issue with Vitest Snapshot
Temporary fix for Vitest Snapshot issue and is a continuation of PR #537, we'll probably have to rollback this PR once the Vitest Snapshot bug is resolved. The snapshots are currently incorrect since they are sometime escaped with single quote and sometime without any quotes. Again this is a temp fix and Vitest will hopefully provide a fix to their snapshots, this temp fix should allow CI to pass
ran locally with `vitest --update` to update Vitest Snapshot
> chore: update Vitest snapshot to temporarily proceed with migration

- .github/renovate.json5
- packages/core/package.json
- packages/publish/package.json
- packages/version/package.json
- pnpm-lock.yaml
Update `minimatch` to v8 and also update couple of other dependencies patches. 
update all dependencies to latest
> fix(deps): update dependency minimatch to v8 and couple other deps patch

- .github/workflows/main.yml
> chore: add Node 19 to list of testing environment

- README.md
- package.json
- packages/changed/package.json
- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/cli-commands/__tests__/cli-changed-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-diff-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-exec-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-list-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-publish-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-run-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-version-commands.spec.ts
- packages/cli/src/cli-commands/__tests__/cli-watch-commands.spec.ts
- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/diff/package.json
- packages/exec/package.json
- packages/list/package.json
- packages/publish/README.md
- packages/publish/package.json
- packages/run/package.json
- packages/version/README.md
- packages/version/package.json
- packages/watch/package.json
- pnpm-lock.yaml
Make `version` and `publish` as optional commands. This change will in summary turn every command of the lib as optional commands (except `init` which is a tiny command) and the CLI is now a dependency of all of these optional command. 
This is a breaking change and the users will have to do this change on their end if they still want to use `version` and `publish`
```diff
- "@lerna-lite/cli": "2.0.0",      <-- you could also keep it, it will be installed behind the scene anyway
+ "@lerna-lite/publish": "2.0.0"
+ "@lerna-lite/version": "2.0.0",  <-- you could skip version since it's tightly coupled to the publish pkg
```
Also note that `@lerna-lite/version` is a strict dependency of `@lerna-lite/publish`, so just installing the `publish` package will automatically provide the `version` as …
> feat(publish)!: make version & publish commands optionnal, closes #450

- .vscode/launch.json
- README.md
- package.json
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/project/__tests__/project.spec.ts
- packages/core/src/utils/collect-updates/__tests__/lib-collect-packages.spec.ts
- packages/publish/src/__tests__/get-unpublished-packages.spec.ts
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/publish-tagging.spec.ts
- packages/run/src/__tests__/__snapshots__/run-command.spec.ts.snap
- packages/run/src/__tests__/run-command.spec.ts
- packages/version/src/__tests__/__snapshots__/version-command.spec.ts.snap
- pnpm-lock.yaml
- vitest.config.ts
Update Vitest to latest 0.30.x
> chore(deps): update Vitest to latest and update snapshots to match

- .github/renovate.json5
- package.json
- packages/run/package.json
- packages/run/src/__tests__/run-command-with-nx-no-target-defaults.spec.ts
- packages/run/src/__tests__/run-command-with-nx-not-loaded.spec.ts
- packages/run/src/__tests__/run-command.spec.ts
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- pnpm-lock.yaml
lower Nx version used for optional `useNx` option with `lerna run`
newer Nx versions seems to cause more console warnings and we don't really need to test higher versions since using Nx with `lerna run` is totally optional anyway
> chore(deps): test useNx with lower version of Nx

- packages/run/src/__tests__/run-command-with-nx-no-target-defaults.spec.ts
- packages/version/src/conventional-commits/__tests__/conventional-commits.spec.ts
add back some unit tests that were originally skipped when migrating to Vitest
add as much unit tests as possible
> chore: add skipped conventional commit unit tests & avoid Nx test error

- .github/workflows/main.yml
- package.json
- packages/version/src/__tests__/version-command.spec.ts
- pnpm-lock.yaml
upgrade pnpm 8
use latest pnpm in local project
> chore(deps): upgrade local pnpm to v8

- packages/cli/src/cli-commands/__tests__/cli-version-commands.spec.ts
Add Unit tests to verify the command line is parsed as expected.
Needed to check exactly how `yargs` parsed the command line. Related to #569 and #575 
It is only a test.
> test: Add parsing test for version cli args

- .github/renovate.json5
- package.json
- packages/core/src/__tests__/command.spec.ts
- packages/core/src/utils/collect-updates/__tests__/collect-updates.spec.ts
- packages/core/src/utils/collect-updates/__tests__/lib-make-diff-predicate.spec.ts
- packages/diff/src/__tests__/lib/get-last-commit.spec.ts
- packages/filter-packages/src/__tests__/get-filtered-packages.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/conventional-commits/__tests__/get-commits-since-last-release.spec.ts
- packages/watch/src/__tests__/watch-command.spec.ts
- pnpm-lock.yaml
> chore(deps): update to Vitest v0.31.0 and fix test breaking changes

- packages/publish/src/publish-command.ts
As per Lerna [PR 3674](https://github.com/lerna/lerna/pull/3674)
This will provide access to npm provenance with GitHub Actions https://github.blog/2023-04-19-introducing-npm-package-provenance/
As per Lerna [PR 3674](https://github.com/lerna/lerna/pull/3674), this follows Lerna implementation 
> Provenance is now fully supported when publishing with lerna as of v6.6.2
> 
> All of these methods (from https://docs.npmjs.com/generating-provenance-statements#using-third-party-package-publishing-tools) of letting lerna know about provenance are supported, so choose the one that works best for you:
> 
> <img alt="image" width="710" src="https://user-images.githubusercontent.com/900523/236306370-fcd7efd0-0536-4b1e-96df-7b067e8747ff.png">
> 
> Here is a real example published with lerna:
> 
> …
> feat(publish): add npm provenance to lerna publish

- packages/version/src/__tests__/version-command.spec.ts
unit test is against live pnpm lock file of the project which can be any of 6.x, so let's use match instead
> tests: match pnpm lock file version

- CONTRIBUTING.md
- packages/core/src/__tests__/package.spec.ts
- packages/core/src/package-graph/__tests__/package-graph.spec.ts
- packages/core/src/project/__tests__/project.spec.ts
- packages/publish/src/__tests__/publish-canary.spec.ts
- packages/publish/src/__tests__/publish-command.spec.ts
- packages/publish/src/__tests__/publish-licenses.spec.ts
- packages/publish/src/__tests__/publish-tagging.spec.ts
- packages/run/src/__tests__/__snapshots__/run-command.spec.ts.snap
- packages/run/src/__tests__/run-command.spec.ts
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- pnpm-lock.yaml
continuation of PR #649 
rollback a change made in previous PR #649 and keep using snapshot but add serializer so that it works in single and all at once mode
> chore: add Vitest quote serializer everywhere to avoid no-thread diff

- packages/publish/src/__tests__/__fixtures__/remove-fields/packages/package-6/package.json
- packages/publish/src/__tests__/publish-remove-package-fields.spec.ts
- packages/publish/src/publish-command.ts
Incorrect handle empty scripts
added script field check
publish fail on empty scripts
added test case for this
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
> fix(publish): handle empty scripts section on remove-fields flag

- packages/publish/src/publish-command.ts
As per Lerna [PR 3748](https://github.com/lerna/lerna/pull/3748)
> Ensure the error code ends up as a number.
> Node will throw a different error if the process error code is not a number, which conceals the original error.
> Lerna [issue 3693](https://github.com/lerna/lerna/issues/3693)
> fix(publish): ensure that error code is a number

- package.json
- packages/core/src/utils/collect-uncommitted.ts
- pnpm-lock.yaml
Upgrade to newest Prettier v3 major version
> chore(deps): update dependency prettier to v3

- packages/cli/package.json
- packages/core/package.json
- packages/version/package.json
- packages/version/src/conventional-commits/get-github-commits.ts
- pnpm-lock.yaml
Upgrade `dedent` to latest major version 1.0 and fix an issue where it wasn't being called correctly
fix an issue where it wasn't being called correctly in `get-github-commit`
> fix(deps): update dependency dedent to v1 and fix method call

- package.json
- packages/filter-packages/package.json
- packages/profiler/package.json
- pnpm-lock.yaml
> chore(deps): update to latet NodeJS Types v20

- package.json
- packages/core/package.json
- packages/core/src/child-process.ts
- packages/core/src/command.ts
- packages/diff/package.json
- packages/version/package.json
- packages/version/src/git-clients/github-client.ts
- pnpm-lock.yaml
Update to major version of `execa` v8 and fix types
make a separate PR to fix types that are more strict in v8
> chore(deps): update dependency execa to v8

- package.json
- packages/filter-packages/package.json
- packages/profiler/package.json
- pnpm-lock.yaml
> chore(deps): update @types/node

- package.json
- packages/version/src/__tests__/__snapshots__/version-command.spec.ts.snap
- packages/version/src/__tests__/version-build-metadata.spec.ts
- packages/version/src/__tests__/version-conventional-commits.spec.ts
- packages/version/src/__tests__/version-ignore-changes.spec.ts
- pnpm-lock.yaml
Updates from https://github.com/vitest-dev/vitest/pull/3925#issuecomment-1717602220. Feel free to edit changes of this PR as you see fit. 
Speed improvement 67s -> 24s (locally M2 Air). :rocket:
- `pnpm run test` ✅
> chore(dev-deps): update vitest v1 beta

- package.json
- pnpm-lock.yaml
bump Vitest to latest 1.0-beta1 and also give it a try on Windows, it's faster than before for sure and also supports multi-thread workers :)
> chore(deps): bump Vitest to latest 1.0-beta1

- package.json
- packages/core/src/project/__tests__/project.spec.ts
- pnpm-lock.yaml
fix failing unit test in Vitest 1.0-beta.4 by removing an unnecessary serializer and simply use regex to compare error thrown
> chore(deps): update all non-major dependencies to ^1.0.0-beta.4

- packages/changed/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/exec/package.json
- packages/filter-packages/package.json
- packages/init/package.json
- packages/list/package.json
- packages/listable/package.json
- packages/profiler/package.json
- packages/publish/package.json
- packages/run/package.json
- packages/version/package.json
- packages/watch/package.json
Simple improvement for Lerna-Lite packages published on npm
Improve and simplify package TS Types exports for better support as per [Are the types wrong?](https://arethetypeswrong.github.io) website
Prior to the PR, the website is reporting the following, the right column is totally irrelevant and will be removed by this PR
> chore(build): simplify build & types exports

- .github/workflows/publish-npm-latest.yml
> chore: provide correct email format in release workflow

- packages/publish/src/lib/log-packed.ts
- packages/publish/src/publish-command.ts
Running dry-run should be more explicit in logs 
Remove confusions in logs by explicitly show dry-run in multiple sections
> fix(publish): dry-run execution should be more obvious in logs

- .github/workflows/publish-dry-run.yml
- .github/workflows/publish-npm-latest.yml
- .github/workflows/publish-npm-prompt.yml
- .npmrc
- package.json
improve current release workflows & add dry-run release workflows
for better support of CI releases with npm provenance
> chore: add CI publish release workflows

- packages/core/src/corepack/__tests__/exec-package-manager.spec.ts
- packages/core/src/corepack/exec-package-manager.ts
- packages/core/src/corepack/index.ts
fix missing file extension imports
> chore: fix missing JS file extension on imports

- .github/renovate.json5
- packages/filter-packages/package.json
- pnpm-lock.yaml
update all major deps requiring Node 18. updating 
`multimatch` was skipped because another build issue prevented the update but it's all resolved now so that should work
> chore(deps): update multimatch to v7.0.0

- vitest/vitest.config.ts
> chore: remove unnecessary Vitest option

- .github/workflows/main.yml
Latest codecov GitHub Action requires Codecov token
> chore: add required codecov token

- packages/core/src/command.ts
As per original Lerna [PR 3945](https://github.com/lerna/lerna/pull/3945)
> fix: improve git binary error message

- packages/publish/src/publish-command.ts
potentially and hopefully fixes #813
an issue with `removePackageFields` came up in #813 came up and might be caused by using the wrong variable ref, however I'm not entirely sure that this is the cause of the issue since no reproduction was provided (at least not in way that is reproducible with the same result). Let's hope that this fixes the issue though I'm still not 100% sure, hope for the best
> fix(publish): removePackageFields shouldn't mutate original package.json, fixes #813

- .github/renovate.json5
- package.json
- pnpm-lock.yaml
update Prettier
previous version of Prettier had a regression that changed the format of all `tsconfig.json` by adding comma to all properties, the newer version doesn't have that regression so it's time to update
> chore(deps): update Prettier with regression fix on tsconfig formatting

- .github/workflows/main.yml
- .github/workflows/publish-dry-run.yml
- .github/workflows/publish-npm-beta.yml
- .github/workflows/publish-npm-latest.yml
- .github/workflows/publish-npm-prompt.yml
> chore(deps): update pnpm/action-setup to v3

- packages/changed/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/exec/package.json
- packages/filter-packages/package.json
- packages/init/package.json
- packages/list/package.json
- packages/listable/package.json
- packages/profiler/package.json
- packages/publish/package.json
- packages/run/package.json
- packages/version/package.json
- packages/watch/package.json
> chore: remove unnecessary typesVersions

- .eslintrc.json
- package.json
- pnpm-lock.yaml
migrate from `eslint-plugin-node` to `eslint-plugin-n`
the original `eslint-plugin-node` is no longer maintained, so let's migrate to the suggested alternative
> chore: migrate from eslint-plugin-node to `eslint-plugin-n`

- package.json
- packages/cli/src/cli-commands/cli-changed-commands.ts
- packages/cli/src/cli-commands/cli-diff-commands.ts
- packages/cli/src/cli-commands/cli-exec-commands.ts
- packages/cli/src/cli-commands/cli-list-commands.ts
- packages/cli/src/cli-commands/cli-publish-commands.ts
- packages/cli/src/cli-commands/cli-run-commands.ts
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/cli/src/cli-commands/cli-watch-commands.ts
- packages/core/src/command.ts
- packages/core/src/package-graph/lib/cyclic-package-graph-node.ts
- packages/core/src/package-graph/package-graph.ts
- packages/core/src/package.ts
- packages/core/src/project/lib/apply-extends.ts
- packages/core/src/utils/conf.ts
- packages/core/src/utils/log-package-error.ts
- packages/core/src/utils/npm-conf.ts
- packages/core/src/utils/parse-field.ts
- packages/core/src/utils/pulse-till-done.ts
- packages/core/src/utils/run-lifecycle.ts
- packages/publish/src/lib/get-npm-username.ts
- packages/publish/src/lib/get-two-factor-auth-required.ts
- packages/publish/src/lib/npm-dist-tag.ts
- packages/publish/src/lib/npm-publish.ts
- packages/publish/src/lib/verify-npm-package-access.ts
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/writer-opts.ts
- packages/version/src/conventional-commits/writer-opts-transform.ts
- packages/version/src/utils/otplease.ts
- packages/version/src/version-command.ts
- pnpm-lock.yaml
upgrade to latest ESLint v9 with flat config
upgrade to new major (breaking) version that now requires flat config and remove previous `.eslintrc.json` support
> chore: migrate to ESLint v9 with flat config (part 2)

- packages/version/package.json
- packages/version/src/utils/temp-write.ts
- pnpm-lock.yaml
new major of `make-dir` is now pure ESM
keeping up to date with dependencies
> fix(deps): upgrade `temp-dir` to new major which is now ESM

- package.json
- packages/cli/src/cli-commands/__tests__/cli-version-commands.spec.ts
- pnpm-lock.yaml
- vitest/vitest.config.ts
Upgrade Vitest to 2.0
Vitest 2 will be released in June (next month), so I think it's a good time to start testing it
> chore(tests): upgrade to Vitest 2 Beta.3

- lerna.json
- packages/cli/schemas/lerna-schema.json
- packages/cli/src/cli-commands/cli-version-commands.ts
- packages/core/src/models/command-options.ts
- packages/version/README.md
- packages/version/package.json
- packages/version/src/__tests__/__snapshots__/version-command.spec.ts.snap
- packages/version/src/__tests__/git-push.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/version/src/lib/__mocks__/git-push.ts
- packages/version/src/lib/git-push.ts
- packages/version/src/version-command.ts
- pnpm-lock.yaml
Push Git tags one by one
- possibly fixes #701 
- when running Lerna version in `independent` mode, user could overcome GitHub limit
> feat(version): add `--push-tags-one-by-one`, fixes #701

- packages/version/src/conventional-commits/get-commits-since-last-release.ts
> fix(version): update get last commit hash info regex to support all timezone

- packages/version/src/conventional-commits/__tests__/get-commits-since-last-release.spec.ts
> chore: add unit tests for PR #875 with git last commit with TZ format

- packages/npmlog/src/are-we-there-yet/tracker-stream.ts
- packages/npmlog/src/gauge/__tests__/theme-set.spec.ts
- packages/npmlog/src/gauge/render-template.ts
- packages/npmlog/src/gauge/set-immediate.ts
ignore some lines in unit tests to improve test coverage
> chore: Vitest ignore some errors in Gauge unit tests

- packages/npmlog/src/__tests__/npmlog-basic.spec.ts
- packages/npmlog/src/are-we-there-yet/__tests__/tracker-group.spec.ts
- packages/npmlog/src/are-we-there-yet/__tests__/tracker.spec.ts
- packages/npmlog/src/gauge/__tests__/index.spec.ts
- packages/npmlog/src/gauge/__tests__/render-template.spec.ts
- packages/version/src/conventional-commits/__tests__/conventional-commits.spec.ts
cleanup test summary
Remove some console log of errors showing up in the unit test summary
> chore: remove unnecessary console logs from unit tests

- packages/publish/src/__tests__/publish-from-git.spec.ts
- packages/publish/src/lib/is-npm-js-publish-version-conflict.ts
Ignore publish error code E409
related to this Lerna [commit](https://github.com/lerna/lerna/pull/4033/commits/e41851bc01a89702686c13bc48b4b3a4830e562b) and is in case republishing throws an E409 error with the error message `"Failed to save packument"`
> fix(publish): ignore E409 error when re-publishing to NPM

- packages/core/src/utils/__tests__/object-utils.spec.ts
- packages/core/src/utils/object-utils.ts
better verbose subject description when removing fields from package
> chore(publish): use more descriptive subject when removing pkg fields

- eslint.config.mjs
- package.json
- packages/version/src/conventional-commits/get-changelog-config.ts
- pnpm-lock.yaml
Keep dependencies updated to latest
Preparing for next Typescript-ESLint v8 which is now in Alpha stage and is expected to be released in a month or two (see [Announcing typescript-eslint v8 Beta](https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta))
> chore: bump typescript-eslint to v8 alpha

- .github/workflows/main.yml
run CI workflow on Node 18, 20 and 22
Change Node 21 to 22 since previous one is no longer maintained
> chore: run CI workflow on Node 18, 20 and 22

- packages/core/package.json
- packages/core/src/__tests__/prompt.spec.ts
- packages/core/src/prompt.ts
- pnpm-lock.yaml
Use the new `inquirer` modern approach which is ESM
Since `inquirer` v10, the previous approach is now tagged as being the "legacy" approach and I'm assuming that might be removed in the future (or at least, less supported), so let's migrate to the new approach. Also since the new approach is ESM and targeted to only import what we use, that should decrease our build size even if that might be a slight decrease. 
As mentioned on the `inquirer` GitHub [page](https://github.com/SBoudrias/Inquirer.js/tree/main/packages/inquirer)
> This is the legacy version of Inquirer.js. While it still receives maintenance, it is not actively developed. For the new Inquirer, see [@inquirer/prompts](https://www.npmjs.com/package/@inquirer/prompts).
> fix(core): use inquirer new modern approach to move away from legacy

- package.json
- packages/npmlog/src/npmlog.ts
- pnpm-lock.yaml
Keep up to date with latest version
Latest patch version actually caused a formatting issue, so I had to create a separate PR to fix formatting
> chore(deps): update Prettier to latest and fix failing formatting

- packages/publish/src/lib/index.ts
- packages/publish/src/publish-command.ts
Missing file extension from previous PR #907 caused an npm publish error
Missing file extension from previous PR #907 caused an npm publish error
> fix(version): add missing file extension to fix publish error

- eslint.config.mjs
Cleanup ESLint config
just cleaning up the config file
> chore: cleanup eslint config

- eslint.config.mjs
- package.json
- packages/core/src/__tests__/command.spec.ts
- packages/core/src/__tests__/cyclic-package-graph-node.spec.ts
- packages/core/src/__tests__/prompt.spec.ts
- packages/core/src/utils/__tests__/conf.spec.ts
- packages/core/src/utils/__tests__/env-replace.spec.ts
- packages/core/src/utils/__tests__/pulse-till-done.spec.ts
- packages/init/src/__tests__/init-command.spec.ts
- packages/npmlog/src/__tests__/npmlog-basic.spec.ts
- packages/npmlog/src/__tests__/npmlog-progress.spec.ts
- packages/npmlog/src/are-we-there-yet/__tests__/test-event.ts
- packages/npmlog/src/are-we-there-yet/__tests__/tracker-group.spec.ts
- packages/npmlog/src/are-we-there-yet/__tests__/tracker.spec.ts
- packages/npmlog/src/gauge/__tests__/index.spec.ts
- packages/npmlog/src/gauge/__tests__/render-template.spec.ts
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/__tests__/version-command.spec.ts
- packages/watch/src/__tests__/watch-command.spec.ts
- pnpm-lock.yaml
add `eslint-vitest-plugin` to ESLint flat config and cleanup config, also remove unnecessary parser in config
We should be linting unit tests as well
> chore: add `eslint-vitest-plugin` to eslint flat config

- eslint.config.mjs
small cleanup to lower config size
> chore: cleanup eslint flat config file

- packages/cli/schemas/lerna-schema.json
> Fixing warning "Property extends is not allowed" on "extends" property in user's lerna.json.
As per Lerna's PR 4075
> When user has "extends" property in user's lerna.json, for example,
> 
> ```json
> "extends": "my-base-config"
> ```
> 
> VS Code shows "squiggly" warning _"Property extends is not allowed"_ on the `extends` property:
> 
> ![image](https://private-user-images.githubusercontent.com/32443051/362431380-e2e34003-5578-41fd-8c66-26b1d5721762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4OTA1NTIsIm5iZiI6MTcyNDg5MDI1MiwicGF0aCI6Ii8zMjQ0MzA1MS8zNjI0MzEzODAtZTJlMzQwMDMtNTU3OC00MWZkLThjNjYtMjZiMWQ1NzIxNzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLS …
> fix(schema): add extends property in schema

- packages/cli/schemas/lerna-schema.json
The `useWorkspaces` boolean property was missing in Lerna-Lite Schema
fixes #930
> fix(schema): bool prop `useWorkspaces` missing in Schema, fixes #930

- .github/workflows/main.yml
- .github/workflows/publish-npm-latest.yml
- .github/workflows/publish-npm-prerelease.yml
- .github/workflows/publish-npm-prompt.yml
- package.json
- packages/version/src/__tests__/version-command.spec.ts
- pnpm-lock.yaml
Upgrade to pnpm v9 now that it's been in the wild for a few months 
Vitest uses pnpm v9 and now that Lerna-Lite is in the vitest-ecosystem, we have to make it work with pnpm v9
> chore: upgrade repo to pnpm v9 and fix pnpm unit tests

- .github/renovate.json5
- package.json
I don't want to have to update my local pnpm version every time a new release is out, let's loosen it up a bit
> chore(deps): loosen up pnpm min version requirement

- .github/renovate.json5
> chore: try Renovate locfile maintenance flag

- packages/version/package.json
- pnpm-lock.yaml
remove unused dep
@types/pify isn't necessary since the original project now provide its own types
> chore: remove unnecessary @types/pify

- packages/changed/tsconfig.json
- packages/cli/tsconfig.json
- packages/core/tsconfig.json
- packages/diff/tsconfig.json
- packages/exec/tsconfig.json
- packages/init/tsconfig.json
- packages/list/tsconfig.json
- packages/listable/tsconfig.json
- packages/npmlog/tsconfig.json
- packages/profiler/tsconfig.json
- packages/publish/tsconfig.json
- packages/run/tsconfig.json
- packages/version/tsconfig.json
- packages/watch/tsconfig.json
- tsconfig.base.json
remove fixtures from dist folders
after inspecting the distribution folders, I found out that some of them had fixtures in them which ended up on the publish npm package though we really don't need any of that
> chore: exclude fixtures from built distribution folders

- .github/workflows/main.yml
- package.json
- packages/changed/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/diff/package.json
- packages/exec/package.json
- packages/init/package.json
- packages/list/package.json
- packages/listable/package.json
- packages/npmlog/package.json
- packages/profiler/package.json
- packages/publish/package.json
- packages/run/package.json
- packages/version/package.json
- packages/watch/package.json
Bump minimal NodeJS version requirement to v20.9.0
Prepping for our next major version to coincide with Node 18 EOL
> fix(deps)!: bump minimum Node version to ^20.17.0 || >=22.9.0

- packages/core/src/corepack/__tests__/exec-package-manager.spec.ts
- packages/core/src/package.ts
- packages/core/src/utils/__tests__/env-replace.spec.ts
- packages/core/src/utils/__tests__/parse-field.spec.ts
- packages/core/src/utils/describe-ref.ts
- packages/publish/src/lib/npm-publish.ts
- packages/publish/src/publish-command.ts
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/conventional-commits/__tests__/get-commits-since-last-release.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
- packages/version/src/version-command.ts
- packages/watch/src/watch-command.ts
- scripts/cleanup-temp-files.mjs
This PR removes some unnecessary checks/optional-chaining and wrong await
> refactor: improve codes

- pnpm-lock.yaml
should close security CVE reported, even if this is a dev deps anyway
> chore(deps): update Vite to v6.2.6 to fix vulnerabilities

- .github/renovate.json5
- .github/workflows/main.yml
- .github/workflows/publish-npm-latest.yml
- .github/workflows/publish-npm-prerelease.yml
- .github/workflows/publish-npm-prompt.yml
- package.json
- pnpm-lock.yaml
upgrade to pnpm@10
pnpm v10 has been out for a few months already so I think it's stable enough to upgrade
> chore(deps): upgrade to pnpm v10

- packages/core/src/utils/collect-updates/__tests__/lib-make-diff-predicate.spec.ts
- packages/core/src/utils/collect-updates/lib/make-diff-predicate.ts
continues on PR #1023
another fix for issue #1010 since I forgot to add local deps check in previous PR #1023
> fix: pnpm local catalog changes should be reflected in packages

- package.json
- packages/version/src/conventional-commits/__fixtures__/fixed/scripts/erroring-preset.ts
- pnpm-lock.yaml
- vitest/vitest.config.ts
Update Vite/Vitest to latest versions
reimplement closed PR #1030 with latest Vite that fixes a test regression observed in PR #1024
> chore(deps): update to latest Vite/Vitest versions

- .github/workflows/main.yml
Run tests on Node 24 as well, that is on top of actual Node 20, 22
Tests on all supported Node versions
> chore: also run tests on new Node 24 (on top of Node 20, 22)

- .github/renovate.json5
- package.json
- packages/version/package.json
- packages/version/src/conventional-commits/get-changelog-config.ts
- packages/version/src/conventional-commits/update-changelog.ts
- pnpm-lock.yaml
code cleanup
just some code cleanup about the recent refactoring of conventional-changelog changes
> chore: code cleanup in recent conventional-changelog refactoring

- helpers/fixtures.ts
- helpers/index.ts
- helpers/serializers/serialize-tempdir.ts
- package.json
- packages/core/src/__tests__/command.spec.ts
- packages/core/src/project/__tests__/project.spec.ts
- packages/init/src/__tests__/init-command.spec.ts
- packages/listable/src/__tests__/listable-format.spec.ts
- packages/publish/package.json
- packages/publish/src/publish-command.ts
- packages/version/package.json
- packages/version/src/__tests__/version-bump-prerelease.spec.ts
- packages/version/src/lib/__mocks__/load-json-file.ts
- packages/version/src/utils/temp-write.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- scripts/cleanup-temp-files.mjs
remove `temp-dir`, `tempy` and `make-dir`
replace some dependencies with native code to decrease download and build size
existing unit tests
> feat(deps): replace `temp-dir`, `tempy` and `make-dir` with native code

- packages/core/src/package.ts
simple code refactoring
simplify code logic
> chore(publish): simplify workspace: protocol code logic

- __fixtures__/lockfile-bun/bun.lock
- __fixtures__/lockfile-bun/package.json
- __fixtures__/lockfile-bun/packages/package-1/package.json
- __fixtures__/lockfile-bun/packages/package-2/package.json
- __fixtures__/lockfile-bun/packages/package-3/package.json
- __fixtures__/lockfile-bun/packages/package-4/package.json
- packages/version/src/__tests__/update-lockfile-version.spec.ts
- packages/version/src/lib/update-lockfile-version.ts
https://bun.com/docs/install/lockfile
https://bun.sh/docs/install/lifecycle#ignore-scripts
Resolves #1100
> feat: add `syncWorkspaceLock` support for bun

- helpers/fixtures.ts
- package.json
- pnpm-lock.yaml
Remove another dev dependency
Dependencies Cleanup
> chore(deps): remove `file-url` dev dependency

- README.md
- packages/core/package.json
- packages/core/src/filter-packages/lib/filter-packages.ts
- packages/watch/package.json
- packages/watch/src/watch-command.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Code cleanup
I have implementation for picomatch and zeptomatch in the core package, let's only use zeptomatch since it's much smaller and is more maintained than picomatch
> fix(deps): migrate from picomatch to zeptomatch to filter packages

- packages/npmlog/package.json
- packages/npmlog/src/gauge/__tests__/index.spec.ts
- pnpm-lock.yaml
remove external dependency in unit test, just go native
instead of the external dependency when we can simply use native code, this has no impact on the end user since this is only used in a unit test
> chore(deps): remove readable-stream dependency

- packages/core/src/command.ts
- packages/core/src/package.ts
- packages/core/src/project/project.ts
- packages/core/src/utils/npm-conf.ts
- packages/npmlog/src/gauge/has-color.ts
- packages/npmlog/src/gauge/index.ts
- packages/npmlog/src/gauge/plumbing.ts
- packages/npmlog/src/gauge/render-template.ts
- packages/publish/src/lib/get-packed.ts
- packages/publish/src/lib/npm-dist-tag.ts
- packages/publish/src/publish-command.ts
- packages/run/src/lib/timer.ts
- packages/version/src/conventional-commits/recommend-version.ts
simplify code
no need to have an extra `has-color.ts` when there's only 1 line of code anyway, so let's simplify that and increase test coverage
> chore: simplify npmlog has-color
